// The kit-only ratchet gates (docs/ux-system/kit-v2.md §7 G1, §8.4 G15, and
// the new owner rule G16: "No UI component to be used should remain outside
// our kit. All is coming from our library only.", 2026-09-26).
//
// A pure-Dart file scan — no widget pumping. Modelled on
// test/design_standard_test.dart: a committed per-file baseline that only
// shrinks. The test fails when a file/pattern count rises above its
// baseline, or a file/pattern not in the baseline appears at all. When
// counts drop it still passes, but prints the entries that dropped and the
// command that commits the smaller numbers, so they only ever go down. A
// passing run with nothing dropped prints nothing.
//
// G1 — modal and toast entry points live in the kit: outside lib/ui/kit/,
// showDialog(/showModalBottomSheet(/etc. must come from the kit's
// showKit*/Kit* wrappers instead.
// G15 — no width literals outside the kit: lib/ui/ (minus lib/ui/kit/) must
// read window classes from KitLayout, never compare a width to a number
// directly (§8.1).
// G16 — kit-only allowlist: a file under lib/ui/ (minus lib/ui/kit/) may
// only construct the plain layout/scrolling/builder/semantics Flutter
// widgets in `_g16Allowlist`; every other framework widget (Text, Icon,
// buttons, Card, Scaffold, dialogs, ...) must come from the kit. Pages are
// pushed with KitPageRoute (KIT-7): MaterialPageRoute and PageRouteBuilder
// count there and in the Flutter UI code elsewhere under lib/.
// G2, G7, G15x, G17, G21, G48 — docs/ux-system/revamp/STANDARDS.md §18: kit
// seams (copy, haptics, links, motion, retired wrappers), directional layout
// and bidi marks, widths inside the kit, colour roles, look and motion
// literals, and drafts in sheets. One data-driven table, `_rules`.
//
// Regenerate the baseline after a migration lands:
//   KIT_RATCHET_WRITE=1 flutter test test/kit_ratchet_test.dart
// (add KIT_RATCHET_GATES=G17,G21 to rewrite only those gates' baselines)
// (the pinned Flutter from AGENTS.md). Then run it again without the env
// var to prove the new baseline is clean, and commit the smaller numbers.
//
// The Flutter framework widget catalogue this file reads
// (test/kit_ratchet_flutter_widgets.json) is generated by
// tool/kit/flutter_widget_names.dart and should be regenerated whenever the
// pinned Flutter revision (AGENTS.md) changes.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// file -> reason, for G1/G16 exemptions that cannot move into the kit.
/// Keep this empty or near-empty: the kit itself is already out of scope
/// (excluded by directory), so an entry here means a *non-kit* file that
/// genuinely cannot use the kit wrapper (e.g. bootstrap code that runs
/// before the kit's theme is available). Skips the file entirely for both
/// gates.
const _allowed = <String, String>{};

const _g1PatternNames = [
  'showDialog(',
  'showModalBottomSheet(',
  'showGeneralDialog(',
  'AlertDialog(',
  'SimpleDialog(',
  'DraggableScrollableSheet(',
  'showSnackBar(',
  'SnackBar(',
  'MaterialBanner(',
  'showConfirmSheet(',
];

/// Layout/scroll/builder/semantics/route widgets the design standard
/// allows outside the kit (docs/ux-system/kit-v2.md G16). Everything else
/// a G16-scanned file constructs from the Flutter framework is counted.
const _g16Allowlist = <String>{
  // Layout/structure.
  'Column', 'Row', 'Flex', 'Expanded', 'Flexible', 'Spacer', 'Padding',
  'SizedBox', 'Center', 'Align', 'Stack', 'PositionedDirectional', 'Wrap',
  'ConstrainedBox', 'LimitedBox', 'AspectRatio', 'FittedBox', 'SafeArea',
  'Offstage', 'Visibility', 'KeyedSubtree', 'RepaintBoundary',
  'IgnorePointer', 'AbsorbPointer',
  // Scrolling.
  'ListView', 'CustomScrollView', 'SliverList', 'SliverToBoxAdapter',
  'SliverPadding', 'SliverFillRemaining',
  // Builders.
  'Builder', 'StatefulBuilder', 'LayoutBuilder', 'ValueListenableBuilder',
  'ListenableBuilder', 'AnimatedBuilder', 'StreamBuilder', 'FutureBuilder',
  // Semantics/focus/input plumbing.
  'Semantics', 'MergeSemantics', 'ExcludeSemantics', 'Focus', 'FocusScope',
  'FocusTraversalGroup', 'Shortcuts', 'Actions', 'CallbackShortcuts',
  'PopScope', 'Hero',
  // Routes: none. KitPageRoute is the kit's one route (KIT-7), so
  // MaterialPageRoute and PageRouteBuilder left this list and G16 counts
  // them (`_g16Routes`).
};

/// The routes G16 counts although they are not widgets, so the widget
/// catalogue never lists them (KIT-7): a page is pushed with KitPageRoute,
/// pushKitPage or replaceWithKitPage, and every other use is baselined per
/// file and only shrinks. Name -> named constructors (none). Counted in
/// lib/ui (minus the kit) and in the Flutter UI code elsewhere under lib/
/// (`_uiElsewhere`: lib/main.dart, lib/voice/notices.dart, ...), where G16
/// counts only these.
const _g16Routes = <String, List<String>>{
  'MaterialPageRoute': [],
  'PageRouteBuilder': [],
};

/// Scrollbar is allowed only in the one file that owns desktop scroll
/// chrome (docs/ux-system/kit-v2.md §8.3).
const _scrollbarHome = 'lib/ui/desktop/desktop_interaction.dart';

bool _isGenerated(String path) {
  if (path.startsWith('lib/l10n/app_localizations') && path.endsWith('.dart')) {
    return true;
  }
  return path.endsWith('.g.dart') || path.endsWith('.freezed.dart');
}

/// Strips full-line `//` (and `///`) comments, same technique as
/// test/design_standard_test.dart's `_code`, so doc comments never count.
String _stripLineComments(String source) => source
    .split('\n')
    .where((line) => !line.trimLeft().startsWith('//'))
    .join('\n');

String _codeOf(String path) =>
    _stripLineComments(File(path).readAsStringSync());

/// Recursively lists .dart files under [root] (a path relative to the repo
/// root, e.g. 'lib' or 'lib/ui'), as sorted repo-relative POSIX paths,
/// excluding lib/ui/kit/** and generated files.
List<String> _dartFiles(String root) {
  final dir = Directory(root);
  if (!dir.existsSync()) return const [];
  final files =
      dir
          .listSync(recursive: true)
          .whereType<File>()
          .map((f) => f.path.replaceAll(Platform.pathSeparator, '/'))
          .where((p) => p.endsWith('.dart'))
          .where((p) => !p.startsWith('lib/ui/kit/'))
          .where((p) => !_isGenerated(p))
          .toList()
        ..sort();
  return files;
}

// --- G1: modal and toast entry points ---------------------------------

final Map<String, RegExp> _g1Regexes = {
  for (final pattern in _g1PatternNames)
    pattern: RegExp(
      '(?<![A-Za-z0-9_])'
      '${RegExp.escape(pattern.substring(0, pattern.length - 1))}'
      r'(?:<[^>]*>)?\(',
    ),
};

Map<String, int> _countG1(String code) {
  final counts = <String, int>{};
  for (final entry in _g1Regexes.entries) {
    final n = entry.value.allMatches(code).length;
    if (n > 0) counts[entry.key] = n;
  }
  return counts;
}

// --- G15: no width literals ---------------------------------------------

final _g15Re = RegExp(
  r'(?:MediaQuery\.(?:sizeOf|of)\([^)]*\)(?:\.size)?\.width'
  r'|\b[A-Za-z_]\w*\.maxWidth'
  r'|\bwidth)'
  r'\s*(?:<=?|>=?)\s*\d',
);

Map<String, int> _countG15(String code) {
  final n = _g15Re.allMatches(code).length;
  return n > 0 ? {'width-literal': n} : {};
}

// --- G16: kit-only widget allowlist --------------------------------------

final _ctorCallRe = RegExp(
  r'\b([A-Z][A-Za-z0-9_]*)(?:<[^()]*>)?(\.[a-z]\w*)?\(',
);

Map<String, List<String>> _loadFlutterWidgets() {
  final raw =
      jsonDecode(
            File('test/kit_ratchet_flutter_widgets.json').readAsStringSync(),
          )
          as Map<String, dynamic>;
  final widgets = raw['widgets'] as Map<String, dynamic>;
  return {
    for (final entry in widgets.entries)
      entry.key: (entry.value as List<dynamic>).cast<String>(),
  };
}

/// Every class the app itself declares anywhere under lib/, so a name
/// collision with a Flutter widget (unlikely, but possible) is never
/// mistaken for a framework construction.
Set<String> _loadAppDeclaredClasses() {
  final classRe = RegExp(r'\bclass\s+([A-Za-z_]\w*)');
  final names = <String>{};
  for (final path in _dartFiles('lib')) {
    for (final m in classRe.allMatches(_codeOf(path))) {
      names.add(m.group(1)!);
    }
  }
  return names;
}

Map<String, int> _countG16(
  String code,
  String path,
  Map<String, List<String>> widgets,
  Set<String> appClasses,
) {
  final allowlist = path == _scrollbarHome
      ? {..._g16Allowlist, 'Scrollbar'}
      : _g16Allowlist;
  final counts = <String, int>{};
  for (final m in _ctorCallRe.allMatches(code)) {
    final name = m.group(1)!;
    if (allowlist.contains(name)) continue;
    if (appClasses.contains(name)) continue;
    final ctors = widgets[name] ?? _g16Routes[name];
    if (ctors == null) continue; // not a known Flutter framework widget
    final namedPart = m.group(2);
    if (namedPart != null) {
      final ctorName = namedPart.substring(1);
      if (!ctors.contains(ctorName)) continue; // a static method, e.g. .of(
    }
    counts[name] = (counts[name] ?? 0) + 1;
  }
  return counts;
}

/// G16's counts for [path]: every framework widget outside the allowlist
/// in lib/ui (minus the kit), only the `_g16Routes` elsewhere under lib/.
Map<String, int> _g16CountsFor(
  String code,
  String path,
  Map<String, List<String>> widgets,
  Set<String> appClasses,
) => _countG16(
  code,
  path,
  path.startsWith('lib/ui/') ? widgets : const {},
  appClasses,
);

// --- STANDARDS.md §18 gates G2, G7, G15x, G17, G21, G48 -------------------
//
// These six gates are one data-driven table (`_rules` below): each row is a
// gate, a pattern name (the baseline key), the rule ids it enforces, where it
// scans, a per-file allowlist with reasons, and whether it is absolute. A
// ratchet row's per-file counts live in test/kit_ratchet_baseline.json under
// its gate and may only shrink; an absolute row is never written to the
// baseline, so any hit outside its allowlist fails, even in write mode.
//
// When a design change lands (for example the visual-language tokens), the
// patterns stay as they are and only the baseline is regenerated for the
// gates it touched:
//   KIT_RATCHET_WRITE=1 KIT_RATCHET_GATES=G17,G21 flutter test test/kit_ratchet_test.dart
// A regeneration that raises or adds an entry needs `ratchet-tighten: <gate>
// <pattern>` in the commit body (STANDARDS.md KIT-44).

const _kitDir = 'lib/ui/kit/';

/// Where in a root a row looks.
enum _In { outsideKit, insideKit, anywhere }

/// Counts one pattern in [code] (full-line comments stripped) of [path].
typedef _Counter = int Function(String code, String path);

class _Rule {
  _Rule(
    this.gate,
    this.name,
    this.count, {
    required this.ids,
    required this.fix,
    this.roots = const ['lib/ui'],
    this.scope = _In.outsideKit,
    this.allow = const {},
    this.absolute = false,
    this.skipThemeFiles = false,
    this.note,
  });

  final String gate;

  /// The baseline key; unique within [gate].
  final String name;
  final _Counter count;

  /// STANDARDS.md rule ids this row enforces.
  final List<String> ids;

  /// What to do instead, printed with a failure.
  final String fix;

  /// Repo-relative directories scanned. `lib`/`lib/ui` read `.dart` files;
  /// `shaders` reads every file; `assets` checks file names only;
  /// [_uiElsewhere] is the Flutter UI code under `lib/` outside `lib/ui/`.
  final List<String> roots;
  final _In scope;

  /// Exempt files, each with a reason (KIT-5). A key ending in `/` is a
  /// directory prefix; any other key is an exact repo-relative path (no bare
  /// file names, so a same-named file in another folder is never exempt).
  /// The keys are frozen: each must be in the committed `allow` section of
  /// test/kit_ratchet_baseline.json, which write mode never rewrites.
  final Map<String, String> allow;

  /// Absolute rows have no baseline: any hit outside [allow] fails.
  final bool absolute;

  /// G17 and G21 skip app_theme.dart, theme_packs*.dart and theme_roles.dart.
  final bool skipThemeFiles;

  /// Why a row STANDARDS.md calls absolute is a ratchet today.
  final String? note;
}

bool _isThemeFile(String path) {
  final base = path.split('/').last;
  return base == 'app_theme.dart' ||
      base == 'theme_roles.dart' ||
      (base.startsWith('theme_packs') && base.endsWith('.dart'));
}

bool _allowMatches(String key, String path) =>
    key.endsWith('/') ? path.startsWith(key) : path == key;

bool _inScope(_In scope, String path) => switch (scope) {
  _In.outsideKit => !path.startsWith(_kitDir),
  _In.insideKit => path.startsWith(_kitDir),
  _In.anywhere => true,
};

// Counter builders. Each is given code with full-line comments stripped.

_Counter _re(String pattern, {bool caseSensitive = true}) {
  final re = RegExp(pattern, caseSensitive: caseSensitive);
  return (code, _) => re.allMatches(code).length;
}

/// The text between the `(` at [open] and its matching `)` (the rest of
/// [code] if it never closes).
String _argsAt(String code, int open) {
  var depth = 0;
  for (var i = open; i < code.length; i++) {
    final c = code.codeUnitAt(i);
    if (c == 0x28) {
      depth++;
    } else if (c == 0x29) {
      depth--;
      if (depth == 0) return code.substring(open + 1, i);
    }
  }
  return code.substring(open + 1);
}

/// [args] split at top-level commas, trimmed, empty pieces dropped.
List<String> _topLevelArgs(String args) {
  final out = <String>[];
  var depth = 0;
  var start = 0;
  for (var i = 0; i < args.length; i++) {
    final c = args[i];
    if (c == '(' || c == '[' || c == '{') {
      depth++;
    } else if (c == ')' || c == ']' || c == '}') {
      depth--;
    } else if (c == ',' && depth == 0) {
      out.add(args.substring(start, i).trim());
      start = i + 1;
    }
  }
  out.add(args.substring(start).trim());
  return out.where((a) => a.isNotEmpty).toList();
}

/// The expression of the top-level named argument [name] in [args], or null.
String? _namedArg(String args, String name) {
  final re = RegExp('^$name:\\s*');
  for (final arg in _topLevelArgs(args)) {
    final m = re.firstMatch(arg);
    if (m != null) return arg.substring(m.end);
  }
  return null;
}

/// Counts calls of [callee] (regex text, e.g. `EdgeInsets\.only`) whose
/// argument list satisfies [test].
_Counter _call(String callee, bool Function(String args) test) {
  final re = RegExp('(?<![A-Za-z0-9_.\$])(?:$callee)(?:<[^()]*>)?\\(');
  return (code, _) {
    var n = 0;
    for (final m in re.allMatches(code)) {
      if (test(_argsAt(code, m.end - 1))) n++;
    }
    return n;
  };
}

final _ctorDeclAfter = RegExp(r'^\(\s*(?:\{|this\.|super\.)');
final _ctorDeclBefore = RegExp(r'^\s*(?:const\s+|factory\s+)?$');
final _fnDeclBefore = RegExp(
  r'^\s*(?:static\s+)?(?:void|[A-Z]\w*(?:<.*>)?\??)\s+$',
);

/// Counts uses of the class or function [name] (`Name(`, `Name<T>(`, and
/// `Name.named(` when [namedCtors]), not its own declaration.
_Counter _uses(String name, {bool namedCtors = true}) {
  final re = RegExp(
    '(?<![A-Za-z0-9_.\$])$name'
    '${namedCtors ? r'(?:\.[a-z]\w*)?' : ''}'
    r'(?:<[^()]*>)?\(',
  );
  return (code, _) {
    var n = 0;
    for (final m in re.allMatches(code)) {
      final lineStart = code.lastIndexOf('\n', m.start) + 1;
      final before = code.substring(lineStart, m.start);
      final open = code.indexOf('(', m.start + name.length);
      final after = code.substring(open, (open + 40).clamp(0, code.length));
      final isCtorDecl =
          _ctorDeclBefore.hasMatch(before) && _ctorDeclAfter.hasMatch(after);
      if (isCtorDecl || _fnDeclBefore.hasMatch(before)) continue;
      n++;
    }
    return n;
  };
}

/// Numeric literal anywhere in an argument list (not part of a name).
final _numericArg = RegExp(r'(?<![A-Za-z0-9_.$])\d');

bool _isNumber(String? expr) =>
    expr != null && RegExp(r'^\d+(?:\.\d+)?$').hasMatch(expr);

String _squash(String s) => s.replaceAll(RegExp(r'\s+'), '');

/// Icon glyph sizes LOOK-33 allows.
final _iconSizes = {20.0, 22.0, 24.0};

bool _badIconSize(String? expr) =>
    _isNumber(expr) && !_iconSizes.contains(double.parse(expr!));

int _iconSizeCount(String code, String path) {
  final calls = _call(
    r'Icon|ImageIcon',
    (args) => _badIconSize(_namedArg(args, 'size')),
  )(code, path);
  final iconSize = RegExp(
    r'\biconSize:\s*(\d+(?:\.\d+)?)\b',
  ).allMatches(code).where((m) => _badIconSize(m.group(1))).length;
  return calls + iconSize;
}

/// G15's width comparisons, minus a guard against zero (`width > 0` is not a
/// breakpoint).
int _kitWidthComparisons(String code, String path) =>
    _g15Re.allMatches(code).where((m) {
      final literal = RegExp(
        r'\d+(?:\.\d+)?',
      ).matchAsPrefix(code, m.end - 1)!.group(0)!;
      return double.parse(literal) != 0;
    }).length;

/// A layout width is a numeric `width:` of at least this many dp; smaller
/// literal widths are spacing and strokes, which G21 counts.
const _layoutWidthFloor = 100;

final _metalRe = RegExp(r'\b(?:metal|chrome)\w*', caseSensitive: false);

int _metalCount(String code, String path) =>
    _metalRe.allMatches(code).length +
    _metalRe.allMatches(path.split('/').last).length;

/// The calls that open a sheet today: the kit's `showKitSheet(` and the two
/// entry points it replaces, so today's DATA-2 debt is baselined and only
/// shrinks instead of hiding until a file switches to `showKitSheet(`.
final _sheetOpeners = [
  for (final name in [
    'showKitSheet',
    'showModalBottomSheet',
    'showConfirmSheet',
  ])
    _uses(name, namedCtors: false),
];

/// G48: a file that opens a sheet and has a multiline field keeps a draft.
/// Counts the multiline fields of an offending file.
int _g48Count(String code, String path) {
  if (_sheetOpeners.every((opens) => opens(code, path) == 0)) return 0;
  if (RegExp(r'\bdraft:').hasMatch(code)) return 0;
  return RegExp(
    r'KitFieldKind\.multiline|\bmaxLines:\s*null\b|\bminLines:',
  ).allMatches(code).length;
}

/// Old kit names retired by a kit change, name -> the unit that retired it
/// (KIT-43). Append one line per retired name; each becomes a G2 row.
const _retiredApis = <String, String>{};

/// The LOOK-27 files allowed to construct glass whose path is known today.
/// Frozen (KIT-5): the floating tab bar, rail, top controls and desktop
/// sidebar parts have no planned path yet, so the unit that lands one adds
/// its exact path here and to the committed `allow` section of
/// test/kit_ratchet_baseline.json, with `ratchet-tighten: G21
/// KitGlass(/GlassSurface(` in its commit body (KIT-44).
const _glassFiles = <String, String>{
  'lib/ui/kit/glass/': 'the glass part itself (LOOK-27)',
  'lib/ui/kit/chat/kit_composer.dart':
      'the composer is navigation-layer glass (LOOK-27; planned path)',
  'lib/ui/kit/kit_nav.dart':
      'the floating tab bar and rail are navigation-layer glass (LOOK-27)',
  'lib/ui/kit/kit_top_bar.dart':
      'the top controls are navigation-layer glass (LOOK-27)',
  'lib/ui/screens/home_screen.dart':
      'shrinking allowlist until the dock moves into a kit part (LOOK-27)',
  'lib/ui/widgets/glass_surface.dart':
      'shrinking allowlist: the old wrapper forwards to KitGlass (LOOK-27)',
};

/// KitScene drawings (TEST-14) shape their paths with arc and corner radii in
/// the illustration's own coordinate space; LOOK-19 governs surface radii.
const _sceneRadiusFiles = <String, String>{
  ..._tokenFiles,
  'lib/ui/kit/scenes/':
      'KitScene drawings: path radii in the illustration space, not surfaces',
};

/// The look gates, absolute inside `lib/ui/kit/` now that every kit unit
/// has merged (kit-gates-manifest, cut v2 C21 correction): a kit file's G17
/// or G21 hit is never baselined. The exceptions are the kit files an open
/// slice holds right now, which keep their committed baseline entries until
/// that slice brings them to zero; each names its owner, and the map only
/// shrinks (a file that reaches zero must leave it).
const _lookGates = {'G17', 'G21'};
const _kitLookDeferrals = <String, String>{
  'lib/ui/kit/kit_row.dart':
      'slice-R4 (row groups on one inset) holds kit_row.dart',
  'lib/ui/kit/kit_row_parts.dart':
      'slice-R4 (row groups on one inset) holds kit_row_parts.dart',
};

/// Whether [rule]'s hit in [path] is never baselined.
bool _absoluteAt(_Rule rule, String path) =>
    rule.absolute ||
    (_lookGates.contains(rule.gate) &&
        path.startsWith(_kitDir) &&
        !_kitLookDeferrals.containsKey(path));

/// The forced-LTR subtrees where left alignment is correct (LAY-8).
const _forcedLtrFiles = <String, String>{
  'lib/ui/kit/kit_technical_value.dart':
      'KitTechnicalValue is a forced-LTR value',
  'lib/ui/kit/kit_code_block.dart':
      'KitCodeBlock is a forced-LTR block (LAY-8)',
  'lib/ui/kit/kit_log_panel.dart': 'KitLogPanel is a forced-LTR block (LAY-8)',
  'lib/ui/kit/kit_diff_view.dart': 'KitDiffView is a forced-LTR block (LAY-8)',
};

const _tokenFiles = <String, String>{
  'lib/ui/kit/kit_tokens.dart':
      'the token table is where the numbers live (KIT-9)',
  'lib/ui/kit/kit_text.dart':
      'the type roles are where font sizes live (LOOK-12)',
};

/// Left and right given and textually different (a lone `left:` or
/// `right:` counts). `left: x, right: x` is direction-neutral, the same as a
/// symmetric `EdgeInsets.fromLTRB`.
bool _asymmetricLeftRight(String args) {
  final left = _namedArg(args, 'left');
  final right = _namedArg(args, 'right');
  if (left == null && right == null) return false;
  if (left != null && right != null) return _squash(left) != _squash(right);
  return true;
}

/// LOOK-21 inside the kit: a `Border.all(` or `BorderSide(` whose width is
/// missing (the default is one logical pixel) or not read from KitTokens,
/// and a numeric `thickness:` other than 0 (0 is the one-physical-pixel
/// hairline).
int _kitStrokeCount(String code, String path) {
  final strokes = _call(r'Border\.all|BorderSide', (a) {
    if (a.contains('BorderStyle.none')) return false;
    final width = _namedArg(a, 'width');
    return width == null || !width.contains('KitTokens');
  })(code, path);
  final thickness = RegExp(
    r'\bthickness:\s*(\d+(?:\.\d+)?)\b',
  ).allMatches(code).where((m) => double.parse(m.group(1)!) != 0).length;
  return strokes + thickness;
}

final List<_Rule> _rules = [
  // G2 — kit seams: copy, haptics, links, motion, retired wrappers.
  for (final (name, counter, ids, fix)
      in <(String, _Counter, List<String>, String)>[
        (
          'Clipboard.setData(',
          _re(r'\bClipboard\.setData\('),
          ['KIT-23'],
          'use KitCopy.copy(context, text)',
        ),
        (
          'HapticFeedback.',
          _re(r'\bHapticFeedback\.'),
          ['MOT-11'],
          'use KitHaptics',
        ),
        (
          'launchUrl(',
          _re(r'(?<![A-Za-z0-9_.$])launchUrl(?:String)?\('),
          ['SEC-1'],
          'open it through openExternalLink',
        ),
        ('AnimatedSize(', _uses('AnimatedSize'), ['MOT-5'], 'use KitReveal'),
        (
          'ProductErrorState(',
          _uses('ProductErrorState'),
          ['STATE-1', 'KIT-38'],
          'use KitStateView',
        ),
        (
          'ProductEmptyState(',
          _uses('ProductEmptyState'),
          ['STATE-1', 'KIT-38'],
          'use KitStateView',
        ),
        (
          'ProductInlineEmpty(',
          _uses('ProductInlineEmpty'),
          ['STATE-1', 'KIT-38'],
          'use KitStateView',
        ),
        (
          'showConfirmSheet(',
          _uses('showConfirmSheet', namedCtors: false),
          ['KIT-38', 'KIT-43'],
          'use showKitConfirm',
        ),
        (
          'KitSecretField(',
          _uses('KitSecretField'),
          ['KIT-43'],
          'use the kit field in secret mode',
        ),
        for (final MapEntry(key: old, value: unit) in _retiredApis.entries)
          (
            '$old(',
            _uses(old),
            ['KIT-43'],
            'retired by $unit: use its replacement',
          ),
      ])
    _Rule(
      'G2',
      name,
      counter,
      ids: ids,
      fix: fix,
      roots: const ['lib'],
      allow: name == 'launchUrl('
          ? const {
              'lib/ui/widgets/external_link.dart':
                  'openExternalLink is the one place that opens a URL (SEC-1)',
            }
          : const {},
    ),
  _Rule(
    'G2',
    'duration: Duration(',
    _re(r'\b(?:duration|reverseDuration):\s*(?:const\s+)?Duration\('),
    ids: ['MOT-1'],
    fix: 'read the duration from KitMotion',
  ),
  _Rule(
    'G2',
    'Curves.',
    _re(r'\bCurves\.'),
    ids: ['MOT-1'],
    fix: 'read the curve from KitMotion',
  ),
  _Rule(
    'G2',
    'HapticFeedback. in kit',
    _re(r'\bHapticFeedback\.'),
    ids: ['MOT-11'],
    fix: 'call KitHaptics',
    scope: _In.insideKit,
    note:
        'STANDARDS says absolute; terminal_key_bar.dart vibrates directly today, so ratchet until it calls KitHaptics',
    allow: const {
      'lib/ui/kit/motion/kit_haptics.dart':
          'KitHaptics is the one vibration seam',
    },
  ),
  _Rule(
    'G2',
    'Clipboard.setData( in kit',
    _re(r'\bClipboard\.setData\('),
    ids: ['KIT-23'],
    fix: 'call KitCopy.copy',
    scope: _In.insideKit,
    absolute: true,
    allow: const {
      'lib/ui/kit/kit_copy.dart': 'KitCopy is the one copy service (KIT-23)',
    },
  ),
  _Rule(
    'G2',
    'duration: Duration( in kit',
    _re(r'\b(?:duration|reverseDuration):\s*(?:const\s+)?Duration\('),
    ids: ['MOT-1'],
    fix: 'name the duration in kit_motion.dart',
    scope: _In.insideKit,
    absolute: true,
    allow: const {
      'lib/ui/kit/kit_motion.dart': 'KitMotion owns every duration (MOT-1)',
    },
  ),
  _Rule(
    'G2',
    'Curves. in kit',
    _re(r'\bCurves\.'),
    ids: ['MOT-1'],
    fix: 'name the curve in kit_motion.dart',
    scope: _In.insideKit,
    note:
        'STANDARDS says absolute; the kit scenes shape their drawings with Curves today, so ratchet until they read KitMotion curves',
    allow: const {
      'lib/ui/kit/kit_motion.dart': 'KitMotion owns every curve (MOT-1)',
    },
  ),
  _Rule(
    'G2',
    'AnimatedSize( in kit',
    _uses('AnimatedSize'),
    ids: ['MOT-5'],
    fix: 'use KitReveal',
    scope: _In.insideKit,
    absolute: true,
    allow: const {
      'lib/ui/kit/kit_buttons.dart':
          'the KitButton spinner slot may resize (MOT-5)',
    },
  ),
  _Rule(
    'G2',
    'launchUrl( in kit',
    _re(r'(?<![A-Za-z0-9_.$])launchUrl(?:String)?\('),
    ids: ['SEC-1'],
    fix: 'take the URL to openExternalLink (lib/ui/widgets/external_link.dart)',
    scope: _In.insideKit,
    absolute: true,
  ),

  // G7 — directional layout and bidi literals. Each layout pattern is a
  // ratchet outside the kit and absolute inside it ("zero in the kit except
  // the allowlist", §18.2 G7), where only the forced-LTR parts may align left.
  for (final (name, counter, allow)
      in <(String, _Counter, Map<String, String>)>[
        (
          'EdgeInsets.only(left|right:)',
          _call(r'EdgeInsets\.only', _asymmetricLeftRight),
          const {},
        ),
        (
          'EdgeInsets.fromLTRB asymmetric',
          _call(r'EdgeInsets\.fromLTRB', (a) {
            final args = _topLevelArgs(a);
            return args.length == 4 && _squash(args[0]) != _squash(args[2]);
          }),
          const {},
        ),
        (
          'Alignment.centerLeft',
          _re(r'\bAlignment\.centerLeft\b'),
          _forcedLtrFiles,
        ),
        ('Alignment.centerRight', _re(r'\bAlignment\.centerRight\b'), const {}),
        ('TextAlign.left', _re(r'\bTextAlign\.left\b'), _forcedLtrFiles),
        ('TextAlign.right', _re(r'\bTextAlign\.right\b'), const {}),
        (
          'Positioned(left|right:)',
          _call(r'Positioned(?:\.fill)?', _asymmetricLeftRight),
          const {},
        ),
      ])
    for (final inKit in [false, true])
      _Rule(
        'G7',
        inKit ? '$name in kit' : name,
        counter,
        ids: const ['LAY-8'],
        roots: const ['lib'],
        scope: inKit ? _In.insideKit : _In.outsideKit,
        absolute: inKit,
        allow: inKit ? allow : const {},
        fix:
            'use the directional form (start/end, AlignmentDirectional, TextAlign.start/end, PositionedDirectional)',
      ),
  _Rule(
    'G7',
    'bidi literal',
    _re(
      r'[\u2066-\u2069\u200E]|\\u(?:206[6-9]|200[eE])|\\u\{0*(?:206[6-9]|200[eE])\}',
    ),
    ids: ['COPY-30'],
    roots: const ['lib'],
    fix: 'wrap the value with KitBidi.ltr or KitBidi.auto',
  ),

  // G15x — inside the kit only kit_layout.dart owns widths (LAY-2).
  for (final (name, counter) in <(String, _Counter)>[
    ('width-literal', _kitWidthComparisons),
    ('numeric maxWidth:', _re(r'\bmaxWidth:\s*\d')),
    (
      'numeric layout width:',
      (code, _) => RegExp(r'\bwidth:\s*(\d+)(?:\.\d+)?\b')
          .allMatches(code)
          .where((m) => int.parse(m.group(1)!) >= _layoutWidthFloor)
          .length,
    ),
  ])
    _Rule(
      'G15x',
      name,
      counter,
      ids: const ['LAY-2'],
      scope: _In.insideKit,
      note:
          'STANDARDS says absolute after §0.5 step 2 adds the KitLayout '
          'named widths; until then kit parts still hold 600/860/440, so '
          'ratchet',
      fix:
          'name the width in KitLayout and decide layout from the window class',
      allow: const {
        'lib/ui/kit/kit_layout.dart':
            'KitLayout owns the breakpoints and named widths (LAY-2)',
      },
    ),

  // G17 — colour comes from ThemeRoles.
  for (final (name, counter, scope, ids, fix)
      in <(String, _Counter, _In, List<String>, String)>[
        (
          'Color(0x',
          _re(r'\bColor\(0x'),
          _In.anywhere,
          ['LOOK-1'],
          'use a ThemeRoles role',
        ),
        (
          'Color.fromARGB(/fromRGBO(',
          _re(r'\bColor\.from(?:ARGB|RGBO)\('),
          _In.anywhere,
          ['LOOK-1'],
          'use a ThemeRoles role',
        ),
        (
          'Colors.*',
          _re(r'\bColors\.(?!transparent\b)\w+'),
          _In.anywhere,
          ['LOOK-1'],
          'use a ThemeRoles role',
        ),
        (
          '.colorScheme',
          _re(r'\.colorScheme\b'),
          _In.outsideKit,
          ['LOOK-2'],
          'read ThemeRoles.of(context)',
        ),
        (
          '.textTheme',
          _re(r'\.textTheme\b'),
          _In.outsideKit,
          ['LOOK-2'],
          'name a KitText role',
        ),
        (
          '.accent',
          _re(r'\.accent\b'),
          _In.outsideKit,
          ['LOOK-6'],
          'let the kit part draw the accent',
        ),
        (
          'hairline.withValues(',
          _re(r'\bhairline\S*\.withValues\('),
          _In.anywhere,
          ['LOOK-3'],
          'hairline is already translucent',
        ),
        (
          'attention roles',
          _re(
            r'\.(?:attention|attentionFill|onAttentionFill|attentionSurface|attentionLine)\b',
          ),
          _In.outsideKit,
          ['LOOK-4', 'LOOK-24'],
          'use KitNeedsYou or KitRequestCard',
        ),
      ])
    _Rule(
      'G17',
      name,
      counter,
      ids: ids,
      fix: fix,
      roots: _uiRoots,
      scope: scope,
      skipThemeFiles: true,
    ),

  // G21 — look and motion: per-file ratchets outside the kit.
  for (final (name, counter, ids, fix)
      in <(String, _Counter, List<String>, String)>[
        (
          'fontSize:',
          _re(r'\bfontSize:'),
          ['LOOK-12', 'LOOK-13'],
          'name a KitText role',
        ),
        (
          'TextStyle(',
          _re(r'(?<![A-Za-z0-9_.$])TextStyle\('),
          ['LOOK-12'],
          'name a KitText role',
        ),
        (
          'BoxShadow(',
          _re(r'\bBoxShadow\('),
          ['LOOK-20'],
          'use a surface step',
        ),
        ('boxShadow:', _re(r'\bboxShadow:'), ['LOOK-20'], 'use a surface step'),
        (
          'shadows: [',
          _re(r'\bshadows:\s*\['),
          ['LOOK-14', 'LOOK-20'],
          'no text shadow; use a surface step',
        ),
        (
          'ImageFilter.blur',
          _re(r'\bImageFilter\.blur'),
          ['LOOK-22'],
          'blur only behind KitGlass',
        ),
        (
          'BackdropFilter(',
          _re(r'\bBackdropFilter\('),
          ['LOOK-22', 'LOOK-27'],
          'use KitGlass on the navigation layer',
        ),
        (
          'Border.all(',
          _re(r'\bBorder\.all\('),
          ['LOOK-21'],
          'use a kit panel or KitTokens.hairlineWidth',
        ),
        (
          'thickness:',
          _re(r'\bthickness:'),
          ['LOOK-21'],
          'use the kit separator',
        ),
        (
          '.toUpperCase()',
          _re(r'\.toUpperCase\(\)'),
          ['LOOK-15'],
          'sentence case',
        ),
        (
          'gradient(',
          _re(r'\b(?:Radial|Linear|Sweep)Gradient\('),
          ['LOOK-9'],
          'ambient colour belongs to the theme',
        ),
        (
          'Image.asset|network|memory|file(',
          _re(r'\bImage\.(?:asset|network|memory|file)\('),
          ['LOOK-35', 'LOOK-37'],
          'use a kit image part or KitScene',
        ),
        (
          'icon size not 20/22/24',
          _iconSizeCount,
          ['LOOK-33'],
          'use 20, 22 or 24',
        ),
        (
          'PageRouteBuilder(',
          _re(r'\bPageRouteBuilder\('),
          ['MOT-3'],
          'use the kit page route',
        ),
        (
          'transitionsBuilder:',
          _re(r'\btransitionsBuilder:'),
          ['MOT-3'],
          'use KitPageTransitionsBuilder',
        ),
        (
          'KitEffects.of(',
          _re(r'\bKitEffects\.of\('),
          ['MOT-12'],
          'read effects through a kit part',
        ),
        (
          'text scale clamp',
          _re(
            r'\bTextScaler\.linear|\bmaxScaleFactor:|\bTextScaler\.noScaling',
          ),
          ['A11Y-8'],
          'only kit parts clamp text scale',
        ),
        (
          'withOpacity(',
          _re(r'\.withOpacity\('),
          ['LOOK-14'],
          'use an opaque role colour',
        ),
        (
          'Opacity( around text',
          _call(
            r'Opacity',
            (a) => RegExp(
              r'\b(?:Text|RichText|SelectableText|KitText)\b',
            ).hasMatch(a),
          ),
          ['LOOK-14'],
          'use text3 for disabled text',
        ),
        (
          'text role withValues(',
          _re(r'\btext[123]\S*\.withValues\('),
          ['LOOK-14'],
          'text is opaque at rest',
        ),
      ])
    _Rule(
      'G21',
      name,
      counter,
      ids: ids,
      fix: fix,
      roots: _uiRoots,
      skipThemeFiles: true,
    ),

  // G21 — numbers belong to KitTokens and KitText, in and out of the kit.
  for (final (name, counter, scope, ids, fix)
      in <(String, _Counter, _In, List<String>, String)>[
        (
          'BorderRadius.circular(<n>',
          _re(r'\bBorderRadius\.circular\(\s*\d'),
          _In.anywhere,
          ['LOOK-19', 'KIT-9'],
          'use a KitTokens radius',
        ),
        (
          'Radius.circular(<n>',
          _re(r'\bRadius\.circular\(\s*\d'),
          _In.anywhere,
          ['LOOK-19', 'KIT-9'],
          'use a KitTokens radius',
        ),
        (
          'EdgeInsets numeric',
          _call(
            r'EdgeInsets(?:Directional)?\.(?:all|only|symmetric|fromLTRB|fromSTEB)',
            _numericArg.hasMatch,
          ),
          _In.anywhere,
          ['LAY-6', 'LAY-7', 'KIT-9'],
          'use KitTokens spacing or KitScreen',
        ),
        (
          'SizedBox numeric',
          _call(
            r'SizedBox',
            (a) =>
                _isNumber(_namedArg(a, 'width')) ||
                _isNumber(_namedArg(a, 'height')),
          ),
          _In.anywhere,
          ['LAY-7', 'KIT-9'],
          'use KitTokens spacing',
        ),
        (
          'fontSize: <n> in kit',
          _re(r'\bfontSize:\s*\d'),
          _In.insideKit,
          ['LOOK-12', 'KIT-9'],
          'name a KitText role',
        ),
        (
          'BorderSide(width: not KitTokens',
          _call(r'BorderSide', (a) {
            final width = _namedArg(a, 'width');
            return width != null && !width.contains('KitTokens');
          }),
          _In.outsideKit,
          ['LOOK-21'],
          'use KitTokens.hairlineWidth(context) or focusRingWidth(context)',
        ),
        (
          'stroke width not KitTokens in kit',
          _kitStrokeCount,
          _In.insideKit,
          ['LOOK-21'],
          'give Border.all/BorderSide width: KitTokens.hairlineWidth(context) '
              'or focusRingWidth(context); Divider thickness: 0',
        ),
      ])
    _Rule(
      'G21',
      name,
      counter,
      ids: ids,
      fix: fix,
      roots: _uiRoots,
      scope: scope,
      skipThemeFiles: true,
      allow: name == 'Radius.circular(<n>' ? _sceneRadiusFiles : _tokenFiles,
    ),

  // G21 — the absolute rows.
  _Rule(
    'G21',
    'KitGlass(/GlassSurface(',
    (c, p) => _uses('KitGlass')(c, p) + _uses('GlassSurface')(c, p),
    ids: ['LOOK-27'],
    fix: 'glass only on the navigation layer',
    roots: _uiRoots,
    scope: _In.anywhere,
    skipThemeFiles: true,
    note:
        'STANDARDS says absolute; the Appearance glass preview builds KitGlass today, so ratchet until it is a kit miniature tab bar',
    allow: _glassFiles,
  ),
  _Rule(
    'G21',
    'KitSurfaceLevel.glass|raised|tonal',
    _re(r'\bKitSurfaceLevel\.(?:glass|raised|tonal)\b'),
    ids: ['KIT-42'],
    fix: 'use ground or surface1-3',
    roots: _uiRoots,
    scope: _In.anywhere,
    skipThemeFiles: true,
    absolute: true,
  ),
  _Rule(
    'G21',
    'disableAnimationsOf',
    _re(r'\bdisableAnimationsOf\b'),
    ids: ['MOT-8'],
    fix: 'ask KitMotion.reduced(context)',
    roots: _uiRoots,
    scope: _In.anywhere,
    skipThemeFiles: true,
    note:
        'STANDARDS says absolute; screens read reduced motion directly today, so ratchet until they ask KitMotion.reduced',
    allow: const {
      'lib/ui/kit/kit_motion.dart':
          'KitMotion is the one reader of reduced motion (MOT-8)',
    },
  ),
  _Rule(
    'G21',
    'Transform.scale|ScaleTransition in kit',
    _re(r'\bTransform\.scale\b|\bScaleTransition\('),
    ids: ['MOT-2'],
    fix: 'slide or cross-fade',
    scope: _In.insideKit,
    skipThemeFiles: true,
    note:
        'STANDARDS says absolute; KitTabSwitcher scales today (MOT-2 names it), so ratchet until it slides or cross-fades',
  ),
  _Rule(
    'G21',
    'metal|chrome',
    _metalCount,
    ids: ['LOOK-32'],
    fix: 'metal is dropped; rename it',
    roots: const ['lib', 'shaders', 'assets'],
    scope: _In.anywhere,
    note:
        'STANDARDS says absolute; two layout variables are named chrome today, so ratchet until they are renamed',
  ),

  // G48 — multiline input in a kit sheet keeps a draft.
  _Rule(
    'G48',
    'sheet multiline without draft:',
    _g48Count,
    ids: ['DATA-2'],
    fix: 'pass draft: KitDraft to the field',
    roots: const ['lib'],
    scope: _In.anywhere,
  ),
];

/// Pseudo-root: every `.dart` file under `lib/` outside `lib/ui/` that
/// imports Flutter's widget layer (material, widgets or cupertino), such as
/// lib/voice/voice_ui.dart, lib/main.dart and the error widget in
/// lib/diagnostics/app_diagnostics.dart. LOOK-1 and the rest of G17/G21 are
/// not limited to `lib/ui/`, so G17 and G21 scan these too (a PROC-20
/// contract problem against the §18.2 "scans `lib/ui/` only" wording; see
/// the QA record), baselined like every other ratchet row.
const _uiElsewhere = 'lib/**(flutter UI outside lib/ui)';

/// The roots of G17 and G21.
const _uiRoots = ['lib/ui', _uiElsewhere];

final _flutterUiImport = RegExp(
  r'''import\s+['"]package:flutter/(?:material|widgets|cupertino)\.dart['"]''',
);

/// The gates `_rules` covers, in baseline order.
const _ruleGates = ['G2', 'G7', 'G15x', 'G17', 'G21', 'G48'];

final _fileCache = <String, List<String>>{};

/// Files under [root], sorted repo-relative POSIX paths, generated files out.
List<String> _filesUnder(String root) => _fileCache.putIfAbsent(root, () {
  if (root == _uiElsewhere) {
    return [
      for (final path in _filesUnder('lib'))
        if (!path.startsWith('lib/ui/') &&
            _flutterUiImport.hasMatch(File(path).readAsStringSync()))
          path,
    ];
  }
  final dir = Directory(root);
  if (!dir.existsSync()) return const [];
  final files =
      dir
          .listSync(recursive: true)
          .whereType<File>()
          .map((f) => f.path.replaceAll(Platform.pathSeparator, '/'))
          .where((p) => root.startsWith('lib') ? p.endsWith('.dart') : true)
          .where((p) => !_isGenerated(p))
          .toList()
        ..sort();
  return files;
});

final _codeCache = <String, String>{};

String _scanCode(String root, String path) {
  if (root == 'assets') return '';
  return _codeCache.putIfAbsent(path, () => _codeOf(path));
}

/// One rule's hits, path -> count, allowlisted files dropped.
Map<String, int> _scanRule(_Rule rule) {
  final hits = <String, int>{};
  for (final root in rule.roots) {
    for (final path in _filesUnder(root)) {
      if (!_inScope(rule.scope, path)) continue;
      if (rule.skipThemeFiles && _isThemeFile(path)) continue;
      if (rule.allow.keys.any((k) => _allowMatches(k, path))) continue;
      final n = rule.count(_scanCode(root, path), path);
      if (n > 0) hits[path] = n;
    }
  }
  return hits;
}

/// Ratchet rows of [gate] as file -> pattern -> count, plus the problems
/// its absolute rows found.
(Map<String, Map<String, int>>, List<String>) _scanGate(String gate) {
  final current = <String, Map<String, int>>{};
  final absoluteProblems = <String>[];
  for (final rule in _rules.where((r) => r.gate == gate)) {
    final hits = _scanRule(rule);
    for (final MapEntry(key: path, value: n) in hits.entries) {
      if (_absoluteAt(rule, path)) {
        final where = rule.absolute ? 'absolute' : 'absolute in the kit';
        absoluteProblems.add(
          '$gate: $path "${rule.name}" x$n — $where, never baselined: '
          '${rule.fix} (${rule.ids.join(', ')})',
        );
      } else {
        (current[path] ??= {})[rule.name] = n;
      }
    }
  }
  return (current, absoluteProblems);
}

/// Problems for one `_rules` gate: a count above its baseline, or a file or
/// pattern the baseline does not know.
List<String> _ruleProblems(
  String gate,
  Map<String, Map<String, int>> current,
  Map<String, dynamic> baseline,
) {
  final byName = {
    for (final r in _rules.where((r) => r.gate == gate)) r.name: r,
  };
  final problems = <String>[];
  for (final MapEntry(key: path, value: patterns) in current.entries) {
    final baseFile = baseline[path] as Map<String, dynamic>? ?? const {};
    for (final MapEntry(key: pattern, value: count) in patterns.entries) {
      final rule = byName[pattern]!;
      final baseCount = (baseFile[pattern] as num?)?.toInt() ?? 0;
      final how =
          '${rule.fix} (${rule.ids.join(', ')}; STANDARDS.md §18 $gate)';
      if (!baseFile.containsKey(pattern)) {
        problems.add(
          '$gate: $path uses "$pattern" x$count (new — baseline has none) — '
          '$how',
        );
      } else if (count > baseCount) {
        problems.add(
          '$gate: $path "$pattern" rose from $baseCount to $count — $how',
        );
      }
    }
  }
  return problems;
}

/// Baseline entries whose count went down (or whose file is clean or gone),
/// so the smaller number gets committed.
List<String> _drops(
  Map<String, Map<String, int>> current,
  Map<String, dynamic> baseline,
) {
  final drops = <String>[];
  for (final MapEntry(key: path, value: patterns) in baseline.entries) {
    for (final MapEntry(key: pattern, value: count)
        in (patterns as Map<String, dynamic>).entries) {
      final now = current[path]?[pattern] ?? 0;
      if (now < (count as num)) drops.add('$path "$pattern" $count -> $now');
    }
  }
  return drops;
}

// --- Frozen allowlists (KIT-5) --------------------------------------------
//
// "The exemption maps hold at most the entries in the committed baseline
// (they never grow)." Every allowlist key is committed under `allow` in
// test/kit_ratchet_baseline.json as gate -> pattern -> [keys], and `_allowed`
// under "G1/G15/G16" -> "_allowed". Write mode never touches that section, so
// adding a key means editing the JSON by hand with `ratchet-tighten: <gate>
// <pattern>` in the commit body (KIT-44), which G31 checks against the merge
// base. A key dropped from the code only prints a reminder to drop it from
// the JSON too.

const _allowSection = 'allow';
const _legacyAllowGate = 'G1/G15/G16';

/// Every allowlist in the code, gate -> pattern -> keys.
Map<String, Map<String, Set<String>>> _allowlistsInCode(List<_Rule> rules) {
  final out = <String, Map<String, Set<String>>>{
    _legacyAllowGate: {'_allowed': _allowed.keys.toSet()},
  };
  for (final rule in rules.where((r) => r.allow.isNotEmpty)) {
    (out[rule.gate] ??= {})[rule.name] = rule.allow.keys.toSet();
  }
  return out;
}

/// (keys in the code the committed set lacks, committed keys the code no
/// longer has).
(List<String>, List<String>) _allowlistDiff(
  Map<String, Map<String, Set<String>>> inCode,
  Map<String, dynamic> committed,
) {
  final grew = <String>[];
  final shrank = <String>[];
  for (final MapEntry(key: gate, value: patterns) in inCode.entries) {
    final committedGate = committed[gate] as Map<String, dynamic>? ?? const {};
    for (final MapEntry(key: pattern, value: keys) in patterns.entries) {
      final frozen = {
        ...(committedGate[pattern] as List<dynamic>? ?? const [])
            .cast<String>(),
      };
      for (final key in keys.difference(frozen)) {
        grew.add('$gate "$pattern" allows $key');
      }
    }
  }
  for (final MapEntry(key: gate, value: patterns) in committed.entries) {
    for (final MapEntry(key: pattern, value: keys)
        in (patterns as Map<String, dynamic>).entries) {
      final now = inCode[gate]?[pattern] ?? const <String>{};
      for (final key in (keys as List<dynamic>).cast<String>()) {
        if (!now.contains(key)) shrank.add('$gate "$pattern" $key');
      }
    }
  }
  return (grew, shrank);
}

// --- Ratchet mechanics ----------------------------------------------------

Map<String, dynamic> _loadBaseline() {
  final file = File('test/kit_ratchet_baseline.json');
  if (!file.existsSync()) return {};
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Sorts a gate's file -> pattern -> count map, dropping zero entries and
/// empty files, for stable JSON output.
Map<String, Map<String, int>> _sorted(Map<String, Map<String, int>> gate) {
  final files = gate.keys.where((f) => gate[f]!.isNotEmpty).toList()..sort();
  return {
    for (final f in files)
      f: {for (final p in (gate[f]!.keys.toList()..sort())) p: gate[f]![p]!},
  };
}

/// Prints [gate]'s dropped entries and the command that commits them. A
/// passing run with nothing dropped prints nothing.
void _printDrops(
  String gate,
  Map<String, Map<String, int>> current,
  Map<String, dynamic> baseline,
) {
  final drops = _drops(current, baseline);
  if (drops.isEmpty) return;
  stdout.writeln(
    '$gate: ${drops.length} baseline entries dropped — commit the '
    'smaller numbers with KIT_RATCHET_WRITE=1 KIT_RATCHET_GATES=$gate:\n'
    '  ${drops.join('\n  ')}',
  );
}

/// Fails when [current] (file -> pattern -> count, for one gate) rises
/// above [baseline], or introduces a file/pattern the baseline does not
/// know about. Files in `_allowed` are skipped entirely.
List<String> _ratchetProblems(
  String gateName,
  Map<String, Map<String, int>> current,
  Map<String, dynamic> baseline,
) {
  final gateBaseline = baseline;
  final problems = <String>[];
  for (final MapEntry(key: path, value: patterns) in current.entries) {
    if (_allowed.containsKey(path)) continue;
    final baseFile = gateBaseline[path] as Map<String, dynamic>? ?? const {};
    for (final MapEntry(key: pattern, value: count) in patterns.entries) {
      final baseCount = (baseFile[pattern] as num?)?.toInt() ?? 0;
      if (!baseFile.containsKey(pattern)) {
        problems.add(
          '$gateName: $path uses "$pattern" x$count (new — baseline has '
          'none) — use the kit part instead (docs/ux-system/kit-v2.md '
          '§7/§9)',
        );
      } else if (count > baseCount) {
        problems.add(
          '$gateName: $path "$pattern" rose from $baseCount to $count — '
          'use the kit part instead (docs/ux-system/kit-v2.md §7/§9)',
        );
      }
    }
  }
  return problems;
}

void main() {
  final baseline = _loadBaseline();
  final writeMode = Platform.environment['KIT_RATCHET_WRITE'] == '1';

  final g1Current = <String, Map<String, int>>{};
  for (final path in _dartFiles('lib')) {
    final counts = _countG1(_codeOf(path));
    if (counts.isNotEmpty) g1Current[path] = counts;
  }

  final g15Current = <String, Map<String, int>>{};
  for (final path in _dartFiles('lib/ui')) {
    final counts = _countG15(_codeOf(path));
    if (counts.isNotEmpty) g15Current[path] = counts;
  }

  final widgets = _loadFlutterWidgets();
  final appClasses = _loadAppDeclaredClasses();
  final g16Current = <String, Map<String, int>>{};
  for (final path in [..._dartFiles('lib/ui'), ..._filesUnder(_uiElsewhere)]) {
    final counts = _g16CountsFor(_codeOf(path), path, widgets, appClasses);
    if (counts.isNotEmpty) g16Current[path] = counts;
  }

  final ruleCurrent = <String, Map<String, Map<String, int>>>{};
  final ruleAbsolute = <String, List<String>>{};
  for (final gate in _ruleGates) {
    final (current, absoluteProblems) = _scanGate(gate);
    ruleCurrent[gate] = current;
    ruleAbsolute[gate] = absoluteProblems;
  }

  final allCurrent = {
    'G1': g1Current,
    'G15': g15Current,
    'G16': g16Current,
    ...ruleCurrent,
  };

  // KIT_RATCHET_GATES=G17,G21 limits a rewrite to those gates; every other
  // gate keeps its committed baseline untouched.
  final writeGates = Platform.environment['KIT_RATCHET_GATES']
      ?.split(',')
      .map((g) => g.trim())
      .where((g) => g.isNotEmpty)
      .toSet();

  if (writeMode) {
    const encoder = JsonEncoder.withIndent('  ');
    // The frozen `allow` section (KIT-5) and any gate this file does not
    // scan are copied as committed, never regenerated.
    final out = <String, dynamic>{
      for (final g in {...allCurrent.keys, ...baseline.keys})
        g:
            allCurrent.containsKey(g) &&
                (writeGates == null || writeGates.contains(g))
            ? _sorted(allCurrent[g]!)
            : baseline[g],
    };
    File(
      'test/kit_ratchet_baseline.json',
    ).writeAsStringSync('${encoder.convert(out)}\n');
    stdout.writeln(
      'KIT_RATCHET_WRITE=1: wrote test/kit_ratchet_baseline.json for '
      '${writeGates?.join(', ') ?? 'every gate'} '
      '(${[for (final g in allCurrent.keys) '$g: ${allCurrent[g]!.length} files'].join(', ')})',
    );
  }

  test('G1: modal and toast entry points live in the kit', () {
    final problems = writeMode
        ? const <String>[]
        : _ratchetProblems(
            'G1',
            g1Current,
            baseline['G1'] as Map<String, dynamic>? ?? {},
          );
    if (problems.isEmpty && !writeMode) {
      _printDrops(
        'G1',
        g1Current,
        baseline['G1'] as Map<String, dynamic>? ?? {},
      );
    }
    expect(problems, isEmpty, reason: problems.join('\n'));
  });

  test('G15: no width literals outside the kit', () {
    final problems = writeMode
        ? const <String>[]
        : _ratchetProblems(
            'G15',
            g15Current,
            baseline['G15'] as Map<String, dynamic>? ?? {},
          );
    if (problems.isEmpty && !writeMode) {
      _printDrops(
        'G15',
        g15Current,
        baseline['G15'] as Map<String, dynamic>? ?? {},
      );
    }
    expect(problems, isEmpty, reason: problems.join('\n'));
  });

  test('G16: every UI component comes from the kit', () {
    final problems = writeMode
        ? const <String>[]
        : _ratchetProblems(
            'G16',
            g16Current,
            baseline['G16'] as Map<String, dynamic>? ?? {},
          );
    if (problems.isEmpty && !writeMode) {
      _printDrops(
        'G16',
        g16Current,
        baseline['G16'] as Map<String, dynamic>? ?? {},
      );
    }
    expect(problems, isEmpty, reason: problems.join('\n'));
  });

  const ruleGateTitles = {
    'G2': 'G2: copy, haptics, links and motion go through the kit',
    'G7': 'G7: layout is directional and bidi marks come from KitBidi',
    'G15x': 'G15 inside the kit: only kit_layout.dart owns widths',
    'G17': 'G17 colour: every colour comes from a ThemeRoles role',
    'G21': 'G21 look and motion: numbers and effects come from the kit',
    'G48': 'G48 drafts: multiline input in a kit sheet keeps a draft',
  };
  for (final gate in _ruleGates) {
    test(ruleGateTitles[gate]!, () {
      final gateBaseline = baseline[gate] as Map<String, dynamic>? ?? {};
      final problems = [
        ...ruleAbsolute[gate]!,
        if (!writeMode)
          ..._ruleProblems(gate, ruleCurrent[gate]!, gateBaseline),
      ];
      if (problems.isEmpty && !writeMode) {
        _printDrops(gate, ruleCurrent[gate]!, gateBaseline);
      }
      expect(problems, isEmpty, reason: problems.join('\n'));
    });
  }

  test('G17/G21 inside the kit: only deferred files keep a baseline, and '
      'each deferral still needs it', () {
    final problems = <String>[];
    for (final gate in _lookGates) {
      final gateBaseline = baseline[gate] as Map<String, dynamic>? ?? {};
      for (final path in gateBaseline.keys) {
        if (path.startsWith(_kitDir) && !_kitLookDeferrals.containsKey(path)) {
          problems.add(
            '$gate: $path is in the baseline, but the look gates are absolute '
            'in the kit — bring the file to zero and drop its entry',
          );
        }
      }
    }
    for (final MapEntry(key: path, value: owner) in _kitLookDeferrals.entries) {
      expect(owner.length, greaterThan(10), reason: path);
      final hits = _lookGates.any(
        (gate) => ruleCurrent[gate]!.containsKey(path),
      );
      if (!hits) {
        problems.add(
          '$path reached zero in G17 and G21 — drop it from _kitLookDeferrals '
          'and its baseline entries (the deferrals only shrink)',
        );
      }
    }
    expect(problems, isEmpty, reason: problems.join('\n'));
  });

  test('allowlists never grow (KIT-5)', () {
    final (grew, shrank) = _allowlistDiff(
      _allowlistsInCode(_rules),
      baseline[_allowSection] as Map<String, dynamic>? ?? const {},
    );
    if (grew.isEmpty && shrank.isNotEmpty) {
      stdout.writeln(
        'KIT-5: ${shrank.length} allowlist keys left the code — drop them '
        'from "$_allowSection" in test/kit_ratchet_baseline.json:\n'
        '  ${shrank.join('\n  ')}',
      );
    }
    expect(
      grew,
      isEmpty,
      reason: [
        for (final g in grew)
          'KIT-5: $g — not in the committed "$_allowSection" set of '
              'test/kit_ratchet_baseline.json. Exemption maps never grow; fix '
              'the file instead, or (the coordinator or the unit the rule '
              'names) add the key to the JSON by hand with '
              '`ratchet-tighten: <gate> <pattern>` in the commit body (KIT-44).',
      ].join('\n'),
    );
  });

  test('allowlist keys are exact paths or folders under lib/', () {
    for (final keys in _allowlistsInCode(_rules).values) {
      for (final key in keys.values.expand((k) => k)) {
        expect(key, startsWith('lib/'), reason: key);
        expect(key.endsWith('/') || key.endsWith('.dart'), isTrue, reason: key);
      }
    }
  });

  test('every G2/G7/G15x/G17/G21/G48 row is named once and has a reason', () {
    for (final gate in _ruleGates) {
      final names = [
        for (final r in _rules.where((r) => r.gate == gate)) r.name,
      ];
      expect(names.toSet().length, names.length, reason: gate);
    }
    for (final rule in _rules) {
      expect(rule.ids, isNotEmpty, reason: rule.name);
      expect(rule.fix.trim(), isNotEmpty, reason: rule.name);
      for (final MapEntry(key: file, value: reason) in rule.allow.entries) {
        expect(reason.trim().length, greaterThan(10), reason: file);
      }
    }
    // Absolute rows are never in the baseline.
    for (final rule in _rules.where((r) => r.absolute)) {
      final gateBaseline = baseline[rule.gate] as Map<String, dynamic>? ?? {};
      for (final entry in gateBaseline.values) {
        expect(
          (entry as Map<String, dynamic>).containsKey(rule.name),
          isFalse,
          reason: '${rule.gate} "${rule.name}" is absolute',
        );
      }
    }
  });

  test('every allowlist entry gives a real reason', () {
    for (final MapEntry(key: path, value: reason) in _allowed.entries) {
      expect(reason.trim().length, greaterThan(10), reason: path);
    }
  });

  test('the Flutter widget catalogue exists and is non-trivial', () {
    final file = File('test/kit_ratchet_flutter_widgets.json');
    expect(file.existsSync(), isTrue);
    final raw = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    expect(raw['flutterRevision'], isNotEmpty);
    final widgets = raw['widgets'] as Map<String, dynamic>;
    expect(
      widgets.length,
      greaterThan(300),
      reason:
          'tool/kit/flutter_widget_names.dart should have found the '
          'bulk of material/widgets/cupertino widget classes',
    );
    // Sanity checks from the spec.
    for (final name in [
      'Text',
      'Icon',
      'Container',
      'Scaffold',
      'AlertDialog',
      'ListTile',
      'FilledButton',
      'TextField',
      'CupertinoButton',
      'Theme',
    ]) {
      expect(widgets.containsKey(name), isTrue, reason: name);
    }
    for (final name in [
      'ThemeData',
      'TextStyle',
      'EdgeInsets',
      'BoxDecoration',
    ]) {
      expect(widgets.containsKey(name), isFalse, reason: name);
    }
  });

  group('counters on fixture strings (proves the regexes, not just files)', () {
    test('G1 matches showDialog<T>( but not showKitDialog( or a comment', () {
      const source = '''
final x = showDialog<bool>(context: context, builder: (_) => null);
showKitDialog(context: context);
_showDialog(context: context);
// showDialog(context: context);
''';
      final counts = _countG1(_stripLineComments(source));
      expect(counts, {'showDialog(': 1});
    });

    test('SnackBar( does not count showSnackBar( or KitSnackBar(', () {
      const source = '''
ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('hi')));
KitSnackBar(message: 'hi');
''';
      final counts = _countG1(_stripLineComments(source));
      expect(counts, {'showSnackBar(': 1, 'SnackBar(': 1});
    });

    test(
      'G16 counts real widget constructions, not static members or app classes',
      () {
        const source = '''
final a = showDialog<bool>(
  context: context,
  builder: (_) => const Text('a'),
);
Theme.of(context);
FilledButton.icon(onPressed: () {}, label: const Text('b'));
// Text(ignored, inside a comment)
KitButton(label: 'c');
MyAppWidget();
''';
        final widgets = _loadFlutterWidgets();
        // A tiny stand-in app-class set: only MyAppWidget is "app-declared"
        // here, so KitButton (not a real Flutter widget name) is dropped by
        // the "not a known widget" branch instead, exactly as it would be
        // for any other kit part.
        final appClasses = {'MyAppWidget'};
        final counts = _countG16(
          _stripLineComments(source),
          'lib/ui/screens/fixture_only.dart',
          widgets,
          appClasses,
        );
        expect(counts, {'Text': 2, 'FilledButton': 1});
      },
    );

    test(
      'KIT-7: a new MaterialPageRoute( in a file with no baseline entry fails '
      'G16, in lib/ui and in UI code elsewhere under lib/',
      () {
        const source = '''
Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => page));
Navigator.of(context).push(
  PageRouteBuilder<void>(pageBuilder: (_, _, _) => page),
);
pushKitPage<void>(context, (_) => page);
Navigator.of(context).push(KitPageRoute<void>(builder: (_) => page));
final isPage = route is MaterialPageRoute;
// MaterialPageRoute(builder: ignored, inside a comment)
''';
        expect(_g16Allowlist, isNot(contains('MaterialPageRoute')));
        expect(_g16Allowlist, isNot(contains('PageRouteBuilder')));
        final widgets = _loadFlutterWidgets();
        const appClasses = {'KitPageRoute'};
        final committed = baseline['G16'] as Map<String, dynamic>? ?? {};
        for (final path in [
          'lib/ui/screens/kit7_fixture_only.dart',
          'lib/voice/kit7_fixture_only.dart',
        ]) {
          expect(committed.containsKey(path), isFalse, reason: path);
          final counts = _g16CountsFor(
            _stripLineComments(source),
            path,
            widgets,
            appClasses,
          );
          expect(counts, {
            'MaterialPageRoute': 1,
            'PageRouteBuilder': 1,
          }, reason: path);
          final problems = _ratchetProblems('G16', {path: counts}, committed);
          expect(problems, hasLength(2), reason: path);
          expect(
            problems,
            contains(
              contains('$path uses "MaterialPageRoute" x1 (new — baseline '),
            ),
          );
        }

        // A file with a baseline entry may not add one either.
        const mainFile = 'lib/main.dart';
        final base =
            ((committed[mainFile]
                        as Map<String, dynamic>?)?['MaterialPageRoute']
                    as num?)
                ?.toInt();
        expect(base, isNotNull, reason: 'KIT-7 baselines $mainFile\'s routes');
        final rose = _ratchetProblems('G16', {
          mainFile: {'MaterialPageRoute': base! + 1},
        }, committed);
        expect(rose.single, contains('rose from $base to ${base + 1}'));
      },
    );

    test(
      'G15 counts a width compared to a literal, not BoxConstraints(maxWidth: n)',
      () {
        const source = '''
final wide = constraints.maxWidth >= 840;
final narrow = MediaQuery.sizeOf(context).width < 600;
return Container(constraints: const BoxConstraints(maxWidth: 560));
''';
        final counts = _countG15(source);
        expect(counts, {'width-literal': 2});
      },
    );
  });

  group('G2/G7/G15x/G17/G21/G48 rows on fixture strings', () {
    int count(String gate, String name, String source, {String? path}) {
      final rule = _rules.singleWhere((r) => r.gate == gate && r.name == name);
      return rule.count(
        _stripLineComments(source),
        path ?? 'lib/ui/screens/fixture_only.dart',
      );
    }

    test('G2 counts uses of an old API, not its declaration', () {
      const source = '''
class ProductEmptyState extends StatelessWidget {
  const ProductEmptyState({super.key, required this.title});
}
Future<bool> showConfirmSheet(BuildContext context) async => true;
final a = ProductEmptyState(title: 'x');
final b = ProductEmptyState.compact(title: 'y');
final ok = await showConfirmSheet(context);
// ProductEmptyState(title: 'a comment')
''';
      expect(count('G2', 'ProductEmptyState(', source), 2);
      expect(count('G2', 'showConfirmSheet(', source), 1);
    });

    test('G2 counts motion literals and seams, not KitMotion names', () {
      const source = '''
AnimatedOpacity(duration: const Duration(milliseconds: 200), curve: Curves.easeOut);
AnimatedOpacity(duration: KitMotion.quick, curve: KitMotion.enter);
Clipboard.setData(ClipboardData(text: t));
HapticFeedback.lightImpact();
launchUrl(uri); launchUrlString('x'); openExternalLink(context, uri);
''';
      expect(count('G2', 'duration: Duration(', source), 1);
      expect(count('G2', 'Curves.', source), 1);
      expect(count('G2', 'Clipboard.setData(', source), 1);
      expect(count('G2', 'HapticFeedback.', source), 1);
      expect(count('G2', 'launchUrl(', source), 2);
    });

    test('SEC-1: launchUrl in the kit is absolute with no allowlist', () {
      final rule = _rules.singleWhere(
        (r) => r.gate == 'G2' && r.name == 'launchUrl( in kit',
      );
      expect(rule.absolute, isTrue);
      expect(rule.allow, isEmpty);
      expect(_inScope(rule.scope, 'lib/ui/kit/kit_link_row.dart'), isTrue);
      expect(
        count(
          'G2',
          'launchUrl( in kit',
          'onTap: () => launchUrl(Uri.parse(value));',
          path: 'lib/ui/kit/kit_link_row.dart',
        ),
        1,
      );
    });

    test('G7 counts left/right layout, not the directional forms', () {
      const source = '''
EdgeInsets.only(left: 8, top: 4);
EdgeInsets.only(left: 8, right: 8, top: 4);
EdgeInsets.only(left: 8, right: 12);
EdgeInsets.only(top: 4);
EdgeInsetsDirectional.only(start: 8);
EdgeInsets.fromLTRB(12, 0, 16, 0);
EdgeInsets.fromLTRB(16, 8, 16, 0);
EdgeInsets.fromLTRB(KitTokens.space4, 0, KitTokens.space4, 8);
Positioned(left: 0, child: x);
Positioned(top: 0, left: 0, right: 0, child: x);
PositionedDirectional(start: 0, child: x);
Alignment.centerLeft; AlignmentDirectional.centerStart;
TextAlign.right; TextAlign.end;
final s = 'a\\u2066b';
''';
      expect(count('G7', 'EdgeInsets.only(left|right:)', source), 2);
      expect(count('G7', 'EdgeInsets.fromLTRB asymmetric', source), 1);
      expect(count('G7', 'Positioned(left|right:)', source), 1);
      expect(count('G7', 'Alignment.centerLeft', source), 1);
      expect(count('G7', 'TextAlign.right', source), 1);
      expect(count('G7', 'bidi literal', source), 1);
    });

    test('G7 is absolute in the kit, forced-LTR parts may align left', () {
      for (final rule in _rules.where(
        (r) => r.gate == 'G7' && r.name.endsWith(' in kit'),
      )) {
        expect(rule.absolute, isTrue, reason: rule.name);
        expect(rule.scope, _In.insideKit, reason: rule.name);
        final left = rule.name.contains('Left') || rule.name.contains('.left');
        expect(
          rule.allow.keys.toSet(),
          left ? _forcedLtrFiles.keys.toSet() : isEmpty,
        );
      }
      expect(
        _rules
            .where((r) => r.gate == 'G7' && r.name.endsWith(' in kit'))
            .length,
        7,
      );
    });

    test('G15x counts breakpoints and layout widths, not guards or gaps', () {
      const source = '''
if (constraints.maxWidth >= 600) {}
final px = size.width > 0 ? 1 : 0;
const BoxConstraints(maxWidth: 860);
SizedBox(width: 720);
SizedBox(width: 8);
''';
      expect(count('G15x', 'width-literal', source), 1);
      expect(count('G15x', 'numeric maxWidth:', source), 1);
      expect(count('G15x', 'numeric layout width:', source), 1);
    });

    test('G17 counts literal colours and theme reads, not transparent', () {
      const source = '''
const c = Color(0xFF112233);
Colors.red; Colors.transparent; Colors.white70;
Theme.of(context).colorScheme.primary; theme.textTheme;
roles.accent; roles.attentionFill; l10n.attentionTitle;
roles.hairline.withValues(alpha: 0.5);
''';
      expect(count('G17', 'Color(0x', source), 1);
      expect(count('G17', 'Colors.*', source), 2);
      expect(count('G17', '.colorScheme', source), 1);
      expect(count('G17', '.textTheme', source), 1);
      expect(count('G17', '.accent', source), 1);
      expect(count('G17', 'attention roles', source), 1);
      expect(count('G17', 'hairline.withValues(', source), 1);
    });

    test('G21 counts look literals the way the rulebook writes them', () {
      const source = '''
BorderRadius.circular(12); Radius.circular(8); BorderRadius.circular(KitTokens.radius);
EdgeInsets.all(16); EdgeInsets.all(KitTokens.space4);
SizedBox(height: 8); SizedBox(height: KitTokens.space2);
Icon(AppIcons.copy, size: 18); Icon(AppIcons.copy, size: 20); Icon(i, size: s);
IconButton(iconSize: 16, onPressed: null, icon: x);
Opacity(opacity: 0.5, child: Text('a')); Opacity(opacity: 0.5, child: Icon(i));
BorderSide(width: 1); BorderSide(width: KitTokens.hairlineWidth(context)); BorderSide(color: c);
label.toUpperCase();
''';
      expect(count('G21', 'BorderRadius.circular(<n>', source), 1);
      expect(count('G21', 'Radius.circular(<n>', source), 1);
      expect(count('G21', 'EdgeInsets numeric', source), 1);
      expect(count('G21', 'SizedBox numeric', source), 1);
      expect(count('G21', 'icon size not 20/22/24', source), 2);
      expect(count('G21', 'Opacity( around text', source), 1);
      expect(count('G21', 'BorderSide(width: not KitTokens', source), 1);
      expect(count('G21', '.toUpperCase()', source), 1);
    });

    test('G21 LOOK-21 in the kit: every stroke width comes from KitTokens', () {
      const source = '''
Border.all(color: c, width: 1.5);
Border.all(color: c);
Border(bottom: BorderSide(color: c));
BorderSide(color: c, width: KitTokens.hairlineWidth(context));
Border.all(color: c, width: KitTokens.focusRingWidth(context));
BorderSide(style: BorderStyle.none);
Divider(thickness: 1); Divider(thickness: 0); Divider(thickness: t);
''';
      const kit = 'lib/ui/kit/kit_fixture.dart';
      expect(
        count('G21', 'stroke width not KitTokens in kit', source, path: kit),
        4,
      );
      final rule = _rules.singleWhere(
        (r) => r.gate == 'G21' && r.name == 'stroke width not KitTokens in kit',
      );
      expect(rule.scope, _In.insideKit);
      final outside = _rules.singleWhere(
        (r) => r.gate == 'G21' && r.name == 'BorderSide(width: not KitTokens',
      );
      expect(outside.scope, _In.outsideKit);
    });

    test('G21 metal/chrome reads identifiers and file names', () {
      const source = 'final chromeBar = 1; final monochrome = 2;';
      expect(count('G21', 'metal|chrome', source), 1);
      expect(
        count('G21', 'metal|chrome', '', path: 'assets/metal_ring.png'),
        1,
      );
    });

    test('G48 flags a sheet with a multiline field and no draft', () {
      const offending = '''
await showKitSheet<void>(context: context, builder: (_) => KitField(maxLines: null));
''';
      const kept = '''
await showKitSheet<void>(context: context, builder: (_) => KitField(maxLines: null, draft: d));
''';
      const noSheet = 'KitField(maxLines: null);';
      const flutterSheet = '''
await showModalBottomSheet<void>(context: context, builder: (_) => TextField(minLines: 3, maxLines: null));
''';
      const confirmSheet = '''
await showConfirmSheet(context, body: TextField(maxLines: null));
''';
      expect(count('G48', 'sheet multiline without draft:', offending), 1);
      expect(count('G48', 'sheet multiline without draft:', kept), 0);
      expect(count('G48', 'sheet multiline without draft:', noSheet), 0);
      expect(count('G48', 'sheet multiline without draft:', flutterSheet), 2);
      expect(count('G48', 'sheet multiline without draft:', confirmSheet), 1);
    });

    test('G17 and G21 also scan Flutter UI code outside lib/ui/', () {
      final elsewhere = _filesUnder(_uiElsewhere);
      expect(
        elsewhere,
        containsAll([
          'lib/voice/voice_ui.dart',
          'lib/voice/notices.dart',
          'lib/diagnostics/app_diagnostics.dart',
          'lib/main.dart',
        ]),
      );
      expect(elsewhere.where((p) => p.startsWith('lib/ui/')), isEmpty);
      expect(elsewhere, isNot(contains('lib/api2/dialect.dart')));
      for (final rule in _rules.where(
        (r) => (r.gate == 'G17' || r.gate == 'G21') && r.scope != _In.insideKit,
      )) {
        if (rule.name == 'metal|chrome') continue; // scans all of lib/
        expect(rule.roots, contains(_uiElsewhere), reason: rule.name);
      }
    });

    test('theme files, allowlist keys and scopes resolve as documented', () {
      expect(_isThemeFile('lib/ui/app_theme.dart'), isTrue);
      expect(_isThemeFile('lib/ui/theme_packs_generated.dart'), isTrue);
      expect(_isThemeFile('lib/ui/kit/theme_roles.dart'), isTrue);
      expect(_isThemeFile('lib/ui/kit/kit_tokens.dart'), isFalse);
      expect(
        _allowMatches('lib/ui/kit/kit_copy.dart', 'lib/ui/kit/kit_copy.dart'),
        isTrue,
      );
      // A same-named file in a kit subfolder or outside the kit is not exempt.
      expect(
        _allowMatches(
          'lib/ui/kit/kit_copy.dart',
          'lib/ui/kit/links/kit_copy.dart',
        ),
        isFalse,
      );
      expect(
        _allowMatches(
          'lib/ui/kit/kit_copy.dart',
          'lib/ui/screens/kit_copy.dart',
        ),
        isFalse,
      );
      expect(
        _allowMatches('kit_copy.dart', 'lib/ui/kit/kit_copy.dart'),
        isFalse,
      );
      expect(
        _allowMatches('lib/ui/kit/glass/', 'lib/ui/kit/glass/kit_glass.dart'),
        isTrue,
      );
      expect(_inScope(_In.outsideKit, 'lib/ui/kit/kit_row.dart'), isFalse);
      expect(_inScope(_In.insideKit, 'lib/ui/kit/kit_row.dart'), isTrue);
    });

    test('KIT-5: an allowlist key the committed set lacks fails', () {
      final rows = [
        _Rule(
          'G2',
          'Clipboard.setData( in kit',
          _re('x'),
          ids: const ['KIT-23'],
          fix: 'x',
          allow: const {
            'lib/ui/kit/kit_copy.dart': 'KitCopy is the one copy service',
            'lib/ui/kit/links/kit_copy.dart': 'a sneaky second copy seam',
          },
        ),
      ];
      final committed = <String, dynamic>{
        'G2': {
          'Clipboard.setData( in kit': ['lib/ui/kit/kit_copy.dart'],
          'Curves. in kit': ['lib/ui/kit/kit_motion.dart'],
        },
      };
      final (grew, shrank) = _allowlistDiff(_allowlistsInCode(rows), committed);
      expect(grew, [
        'G2 "Clipboard.setData( in kit" allows lib/ui/kit/links/kit_copy.dart',
      ]);
      expect(shrank, ['G2 "Curves. in kit" lib/ui/kit/kit_motion.dart']);
    });
  });
}
