// The kit-only ratchet gates (docs/ux-system/kit-v2.md §7 G1, §8.4 G15, and
// the new owner rule G16: "No UI component to be used should remain outside
// our kit. All is coming from our library only.", 2026-09-26).
//
// A pure-Dart file scan — no widget pumping. Modelled on
// test/design_standard_test.dart: a committed per-file baseline that only
// shrinks. The test fails when a file/pattern count rises above its
// baseline, or a file/pattern not in the baseline appears at all. When
// counts drop it still passes, but prints the smaller baseline to commit so
// the numbers only ever go down (see `_printBaseline` below).
//
// G1 — modal and toast entry points live in the kit: outside lib/ui/kit/,
// showDialog(/showModalBottomSheet(/etc. must come from the kit's
// showKit*/Kit* wrappers instead.
// G15 — no width literals outside the kit: lib/ui/ (minus lib/ui/kit/) must
// read window classes from KitLayout, never compare a width to a number
// directly (§8.1).
// G16 — kit-only allowlist: a file under lib/ui/ (minus lib/ui/kit/) may
// only construct the plain layout/scrolling/builder/semantics/route Flutter
// widgets in `_g16Allowlist`; every other framework widget (Text, Icon,
// buttons, Card, Scaffold, dialogs, ...) must come from the kit.
//
// Regenerate the baseline after a migration lands:
//   KIT_RATCHET_WRITE=1 flutter test test/kit_ratchet_test.dart
// (the pinned Flutter from AGENTS.md). Then run it again without the env
// var to prove the new baseline is clean, and commit the smaller numbers.
//
// The Flutter framework widget catalogue this file reads
// (test/kit_ratchet_flutter_widgets.json) is generated by
// tool/kit/flutter_widget_names.dart and should be regenerated whenever the
// pinned Flutter revision (AGENTS.md) changes.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// file -> reason, for G1/G16 exemptions that cannot move into the kit.
/// Keep this empty or near-empty: the kit itself is already out of scope
/// (excluded by directory), so an entry here means a *non-kit* file that
/// genuinely cannot use the kit wrapper (e.g. bootstrap code that runs
/// before the kit's theme is available). Skips the file entirely for both
/// gates.
const _allowed = <String, String>{};

const _g1PatternNames = [
  'showDialog(',
  'showModalBottomSheet(',
  'showGeneralDialog(',
  'AlertDialog(',
  'SimpleDialog(',
  'DraggableScrollableSheet(',
  'showSnackBar(',
  'SnackBar(',
  'MaterialBanner(',
  'showConfirmSheet(',
];

/// Layout/scroll/builder/semantics/route widgets the design standard
/// allows outside the kit (docs/ux-system/kit-v2.md G16). Everything else
/// a G16-scanned file constructs from the Flutter framework is counted.
const _g16Allowlist = <String>{
  // Layout/structure.
  'Column', 'Row', 'Flex', 'Expanded', 'Flexible', 'Spacer', 'Padding',
  'SizedBox', 'Center', 'Align', 'Stack', 'PositionedDirectional', 'Wrap',
  'ConstrainedBox', 'LimitedBox', 'AspectRatio', 'FittedBox', 'SafeArea',
  'Offstage', 'Visibility', 'KeyedSubtree', 'RepaintBoundary',
  'IgnorePointer', 'AbsorbPointer',
  // Scrolling.
  'ListView', 'CustomScrollView', 'SliverList', 'SliverToBoxAdapter',
  'SliverPadding', 'SliverFillRemaining',
  // Builders.
  'Builder', 'StatefulBuilder', 'LayoutBuilder', 'ValueListenableBuilder',
  'ListenableBuilder', 'AnimatedBuilder', 'StreamBuilder', 'FutureBuilder',
  // Semantics/focus/input plumbing.
  'Semantics', 'MergeSemantics', 'ExcludeSemantics', 'Focus', 'FocusScope',
  'FocusTraversalGroup', 'Shortcuts', 'Actions', 'CallbackShortcuts',
  'PopScope', 'Hero',
  // Routes (not widgets anyway, but harmless to list).
  'MaterialPageRoute', 'PageRouteBuilder',
};

/// Scrollbar is allowed only in the one file that owns desktop scroll
/// chrome (docs/ux-system/kit-v2.md §8.3).
const _scrollbarHome = 'lib/ui/desktop/desktop_interaction.dart';

bool _isGenerated(String path) {
  if (path.startsWith('lib/l10n/app_localizations') && path.endsWith('.dart')) {
    return true;
  }
  return path.endsWith('.g.dart') || path.endsWith('.freezed.dart');
}

/// Strips full-line `//` (and `///`) comments, same technique as
/// test/design_standard_test.dart's `_code`, so doc comments never count.
String _stripLineComments(String source) => source
    .split('\n')
    .where((line) => !line.trimLeft().startsWith('//'))
    .join('\n');

String _codeOf(String path) =>
    _stripLineComments(File(path).readAsStringSync());

/// Recursively lists .dart files under [root] (a path relative to the repo
/// root, e.g. 'lib' or 'lib/ui'), as sorted repo-relative POSIX paths,
/// excluding lib/ui/kit/** and generated files.
List<String> _dartFiles(String root) {
  final dir = Directory(root);
  if (!dir.existsSync()) return const [];
  final files =
      dir
          .listSync(recursive: true)
          .whereType<File>()
          .map((f) => f.path.replaceAll(Platform.pathSeparator, '/'))
          .where((p) => p.endsWith('.dart'))
          .where((p) => !p.startsWith('lib/ui/kit/'))
          .where((p) => !_isGenerated(p))
          .toList()
        ..sort();
  return files;
}

// --- G1: modal and toast entry points ---------------------------------

final Map<String, RegExp> _g1Regexes = {
  for (final pattern in _g1PatternNames)
    pattern: RegExp(
      '(?<![A-Za-z0-9_])'
      '${RegExp.escape(pattern.substring(0, pattern.length - 1))}'
      r'(?:<[^>]*>)?\(',
    ),
};

Map<String, int> _countG1(String code) {
  final counts = <String, int>{};
  for (final entry in _g1Regexes.entries) {
    final n = entry.value.allMatches(code).length;
    if (n > 0) counts[entry.key] = n;
  }
  return counts;
}

// --- G15: no width literals ---------------------------------------------

final _g15Re = RegExp(
  r'(?:MediaQuery\.(?:sizeOf|of)\([^)]*\)(?:\.size)?\.width'
  r'|\b[A-Za-z_]\w*\.maxWidth'
  r'|\bwidth)'
  r'\s*(?:<=?|>=?)\s*\d',
);

Map<String, int> _countG15(String code) {
  final n = _g15Re.allMatches(code).length;
  return n > 0 ? {'width-literal': n} : {};
}

// --- G16: kit-only widget allowlist --------------------------------------

final _ctorCallRe = RegExp(
  r'\b([A-Z][A-Za-z0-9_]*)(?:<[^()]*>)?(\.[a-z]\w*)?\(',
);

Map<String, List<String>> _loadFlutterWidgets() {
  final raw =
      jsonDecode(
            File('test/kit_ratchet_flutter_widgets.json').readAsStringSync(),
          )
          as Map<String, dynamic>;
  final widgets = raw['widgets'] as Map<String, dynamic>;
  return {
    for (final entry in widgets.entries)
      entry.key: (entry.value as List<dynamic>).cast<String>(),
  };
}

/// Every class the app itself declares anywhere under lib/, so a name
/// collision with a Flutter widget (unlikely, but possible) is never
/// mistaken for a framework construction.
Set<String> _loadAppDeclaredClasses() {
  final classRe = RegExp(r'\bclass\s+([A-Za-z_]\w*)');
  final names = <String>{};
  for (final path in _dartFiles('lib')) {
    for (final m in classRe.allMatches(_codeOf(path))) {
      names.add(m.group(1)!);
    }
  }
  return names;
}

Map<String, int> _countG16(
  String code,
  String path,
  Map<String, List<String>> widgets,
  Set<String> appClasses,
) {
  final allowlist = path == _scrollbarHome
      ? {..._g16Allowlist, 'Scrollbar'}
      : _g16Allowlist;
  final counts = <String, int>{};
  for (final m in _ctorCallRe.allMatches(code)) {
    final name = m.group(1)!;
    if (allowlist.contains(name)) continue;
    if (appClasses.contains(name)) continue;
    final ctors = widgets[name];
    if (ctors == null) continue; // not a known Flutter framework widget
    final namedPart = m.group(2);
    if (namedPart != null) {
      final ctorName = namedPart.substring(1);
      if (!ctors.contains(ctorName)) continue; // a static method, e.g. .of(
    }
    counts[name] = (counts[name] ?? 0) + 1;
  }
  return counts;
}

// --- Ratchet mechanics ----------------------------------------------------

Map<String, dynamic> _loadBaseline() {
  final file = File('test/kit_ratchet_baseline.json');
  if (!file.existsSync()) return {};
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Sorts a gate's file -> pattern -> count map, dropping zero entries and
/// empty files, for stable JSON output.
Map<String, Map<String, int>> _sorted(Map<String, Map<String, int>> gate) {
  final files = gate.keys.where((f) => gate[f]!.isNotEmpty).toList()..sort();
  return {
    for (final f in files)
      f: {for (final p in (gate[f]!.keys.toList()..sort())) p: gate[f]![p]!},
  };
}

void _printBaseline(Map<String, Map<String, Map<String, int>>> current) {
  final gates = current.keys.toList()..sort();
  final out = {for (final g in gates) g: _sorted(current[g]!)};
  const encoder = JsonEncoder.withIndent('  ');
  // ignore: avoid_print
  print(
    '--- kit_ratchet baseline (commit as test/kit_ratchet_baseline.json '
    'if smaller) ---\n${encoder.convert(out)}\n--- end baseline ---',
  );
}

/// Fails when [current] (file -> pattern -> count, for one gate) rises
/// above [baseline], or introduces a file/pattern the baseline does not
/// know about. Files in `_allowed` are skipped entirely.
List<String> _ratchetProblems(
  String gateName,
  Map<String, Map<String, int>> current,
  Map<String, dynamic> baseline,
) {
  final gateBaseline = baseline;
  final problems = <String>[];
  for (final MapEntry(key: path, value: patterns) in current.entries) {
    if (_allowed.containsKey(path)) continue;
    final baseFile = gateBaseline[path] as Map<String, dynamic>? ?? const {};
    for (final MapEntry(key: pattern, value: count) in patterns.entries) {
      final baseCount = (baseFile[pattern] as num?)?.toInt() ?? 0;
      if (!baseFile.containsKey(pattern)) {
        problems.add(
          '$gateName: $path uses "$pattern" x$count (new — baseline has '
          'none) — use the kit part instead (docs/ux-system/kit-v2.md '
          '§7/§9)',
        );
      } else if (count > baseCount) {
        problems.add(
          '$gateName: $path "$pattern" rose from $baseCount to $count — '
          'use the kit part instead (docs/ux-system/kit-v2.md §7/§9)',
        );
      }
    }
  }
  return problems;
}

void main() {
  final baseline = _loadBaseline();
  final writeMode = Platform.environment['KIT_RATCHET_WRITE'] == '1';

  final g1Current = <String, Map<String, int>>{};
  for (final path in _dartFiles('lib')) {
    final counts = _countG1(_codeOf(path));
    if (counts.isNotEmpty) g1Current[path] = counts;
  }

  final g15Current = <String, Map<String, int>>{};
  for (final path in _dartFiles('lib/ui')) {
    final counts = _countG15(_codeOf(path));
    if (counts.isNotEmpty) g15Current[path] = counts;
  }

  final widgets = _loadFlutterWidgets();
  final appClasses = _loadAppDeclaredClasses();
  final g16Current = <String, Map<String, int>>{};
  for (final path in _dartFiles('lib/ui')) {
    final counts = _countG16(_codeOf(path), path, widgets, appClasses);
    if (counts.isNotEmpty) g16Current[path] = counts;
  }

  final allCurrent = {'G1': g1Current, 'G15': g15Current, 'G16': g16Current};

  if (writeMode) {
    const encoder = JsonEncoder.withIndent('  ');
    final out = {for (final g in allCurrent.keys) g: _sorted(allCurrent[g]!)};
    File(
      'test/kit_ratchet_baseline.json',
    ).writeAsStringSync('${encoder.convert(out)}\n');
    // ignore: avoid_print
    print(
      'KIT_RATCHET_WRITE=1: wrote test/kit_ratchet_baseline.json '
      '(G1: ${g1Current.length} files, G15: ${g15Current.length} files, '
      'G16: ${g16Current.length} files)',
    );
  }

  test('G1: modal and toast entry points live in the kit', () {
    final problems = writeMode
        ? const <String>[]
        : _ratchetProblems(
            'G1',
            g1Current,
            baseline['G1'] as Map<String, dynamic>? ?? {},
          );
    if (problems.isEmpty) _printBaseline(allCurrent);
    expect(problems, isEmpty, reason: problems.join('\n'));
  });

  test('G15: no width literals outside the kit', () {
    final problems = writeMode
        ? const <String>[]
        : _ratchetProblems(
            'G15',
            g15Current,
            baseline['G15'] as Map<String, dynamic>? ?? {},
          );
    expect(problems, isEmpty, reason: problems.join('\n'));
  });

  test('G16: every UI component comes from the kit', () {
    final problems = writeMode
        ? const <String>[]
        : _ratchetProblems(
            'G16',
            g16Current,
            baseline['G16'] as Map<String, dynamic>? ?? {},
          );
    expect(problems, isEmpty, reason: problems.join('\n'));
  });

  test('every allowlist entry gives a real reason', () {
    for (final MapEntry(key: path, value: reason) in _allowed.entries) {
      expect(reason.trim().length, greaterThan(10), reason: path);
    }
  });

  test('the Flutter widget catalogue exists and is non-trivial', () {
    final file = File('test/kit_ratchet_flutter_widgets.json');
    expect(file.existsSync(), isTrue);
    final raw = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    expect(raw['flutterRevision'], isNotEmpty);
    final widgets = raw['widgets'] as Map<String, dynamic>;
    expect(
      widgets.length,
      greaterThan(300),
      reason:
          'tool/kit/flutter_widget_names.dart should have found the '
          'bulk of material/widgets/cupertino widget classes',
    );
    // Sanity checks from the spec.
    for (final name in [
      'Text',
      'Icon',
      'Container',
      'Scaffold',
      'AlertDialog',
      'ListTile',
      'FilledButton',
      'TextField',
      'CupertinoButton',
      'Theme',
    ]) {
      expect(widgets.containsKey(name), isTrue, reason: name);
    }
    for (final name in [
      'ThemeData',
      'TextStyle',
      'EdgeInsets',
      'BoxDecoration',
    ]) {
      expect(widgets.containsKey(name), isFalse, reason: name);
    }
  });

  group('counters on fixture strings (proves the regexes, not just files)', () {
    test('G1 matches showDialog<T>( but not showKitDialog( or a comment', () {
      const source = '''
final x = showDialog<bool>(context: context, builder: (_) => null);
showKitDialog(context: context);
_showDialog(context: context);
// showDialog(context: context);
''';
      final counts = _countG1(_stripLineComments(source));
      expect(counts, {'showDialog(': 1});
    });

    test('SnackBar( does not count showSnackBar( or KitSnackBar(', () {
      const source = '''
ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('hi')));
KitSnackBar(message: 'hi');
''';
      final counts = _countG1(_stripLineComments(source));
      expect(counts, {'showSnackBar(': 1, 'SnackBar(': 1});
    });

    test(
      'G16 counts real widget constructions, not static members or app classes',
      () {
        const source = '''
final a = showDialog<bool>(
  context: context,
  builder: (_) => const Text('a'),
);
Theme.of(context);
FilledButton.icon(onPressed: () {}, label: const Text('b'));
// Text(ignored, inside a comment)
KitButton(label: 'c');
MyAppWidget();
''';
        final widgets = _loadFlutterWidgets();
        // A tiny stand-in app-class set: only MyAppWidget is "app-declared"
        // here, so KitButton (not a real Flutter widget name) is dropped by
        // the "not a known widget" branch instead, exactly as it would be
        // for any other kit part.
        final appClasses = {'MyAppWidget'};
        final counts = _countG16(
          _stripLineComments(source),
          'lib/ui/screens/fixture_only.dart',
          widgets,
          appClasses,
        );
        expect(counts, {'Text': 2, 'FilledButton': 1});
      },
    );

    test(
      'G15 counts a width compared to a literal, not BoxConstraints(maxWidth: n)',
      () {
        const source = '''
final wide = constraints.maxWidth >= 840;
final narrow = MediaQuery.sizeOf(context).width < 600;
return Container(constraints: const BoxConstraints(maxWidth: 560));
''';
        final counts = _countG15(source);
        expect(counts, {'width-literal': 2});
      },
    );
  });
}
