import 'dart:async';

import 'package:flutter/foundation.dart';

import '../domain/agent_account.dart';
import '../domain/provider_quota.dart';
import '../domain/quota_answers.dart';
import '../ui/kit/kit_redact.dart';
import 'quota_answer_preferences.dart';

/// Read-only Remaining answers for one server/profile identity.
///
/// Prefer [QuotaAnswersController.codex] when capabilities.agentAccount is true.
/// The owner supplies a dedicated session from AgentAccountGateway, calls
/// refresh on entry/resume, and disposes this controller on profile/location
/// changes. [isCurrent] must also check profile existence before any async result
/// can land. No provider tokens, account identities or measurements are stored.
/// Only the alert preference survives restart; offline measurements retain their
/// original observation time for this controller's lifetime.
class QuotaAnswersController extends ChangeNotifier {
  final QuotaAnswerPreferences preferences;
  final bool Function() isCurrent;
  final DateTime Function() clock;
  final QuotaAnswerSource source;
  final String serverName;
  final ProviderQuotaGateway Function()? _collectorFactory;
  AgentAccountSession? _session;
  StreamSubscription<AccountEvent>? _events;
  ProviderQuotaGateway? _collector;
  QuotaAnswerSnapshot? _snapshot;
  QuotaAnswerStatus _status = QuotaAnswerStatus.unavailable;
  bool _loading = false;
  bool _stale = true;
  bool _attention = false;
  bool _disposed = false;
  int _revision = 0;
  final Set<String> _alerted = {};
  AgentAccount? _accountIdentity;
  (QuotaProvider, String?)? _collectorIdentity;
  Timer? _expiry;
  DateTime? _expiresAt;

  QuotaAnswersController.codex({
    required AgentAccountSession session,
    required this.preferences,
    required this.isCurrent,
    DateTime Function()? clock,
  }) : source = QuotaAnswerSource.codexAccount,
       serverName = '',
       _collectorFactory = null,
       clock = clock ?? DateTime.now {
    _listen(session);
  }

  /// For an already trusted collector on the selected server. This constructor
  /// does not enroll a monitor, enable background work or install a collector.
  /// Reuses the existing authenticated ProviderQuotaGateway, including its
  /// same-origin and no-redirect security policy. Never use this as a fallback
  /// for a failing Codex account session: that could show a different account.
  QuotaAnswersController.collector({
    required ProviderQuotaGateway Function() gatewayFactory,
    required String serverName,
    required this.preferences,
    required this.isCurrent,
    DateTime Function()? clock,
  }) : source = QuotaAnswerSource.collector,
       serverName = KitRedact.text(serverName),
       _collectorFactory = gatewayFactory,
       clock = clock ?? DateTime.now;

  /// Repository documentation for the operator's existing collector deployment.
  /// No remote script, install command or credential is generated by the app.
  static const collectorSetupGuide = 'tool/quota/README.md';

  bool get _available => !_disposed && isCurrent();
  QuotaAnswerSnapshot? get snapshot => _available ? _snapshot : null;
  QuotaAnswerStatus get status =>
      _available ? _status : QuotaAnswerStatus.unavailable;
  bool get loading => _available && _loading;
  bool get stale =>
      !_available ||
      _stale ||
      (_expiresAt != null && !clock().isBefore(_expiresAt!)) ||
      (_snapshot?.isExpired(clock()) ?? false) ||
      (_snapshot != null && clock().isBefore(_snapshot!.observedAt));
  bool get alert80Enabled => preferences.alert80Enabled;

  /// Foreground attention only. The UI/notification router owns presentation.
  /// This never opts into Android background monitoring or notification access.
  bool get attentionRequired => _available && !stale && _attention;
  Duration? get age => snapshot?.age(clock());

  Future<bool> setAlert80Enabled(bool enabled) async {
    if (!_available) return false;
    final saved = await preferences.setAlert80Enabled(enabled);
    if (!_available) return false;
    if (saved && !enabled) _attention = false;
    _notify();
    return saved;
  }

  void _listen(AgentAccountSession session) {
    _session = session;
    _events = session.events.listen(
      (event) {
        if (!_available) return;
        switch (event.kind) {
          case AccountEventKind.disconnected:
            invalidate();
          case AccountEventKind.changed:
          case AccountEventKind.loginCompleted:
          case AccountEventKind.loginCancelled:
            // An account notification invalidates identity synchronously.
            invalidate(forget: true);
            unawaited(refresh());
          case AccountEventKind.limitsChanged:
            unawaited(refresh());
        }
      },
      onError: (Object _) => invalidate(),
      onDone: invalidate,
    );
  }

  /// After reconnect, supply a new dedicated session for the SAME profile.
  /// Drop the old identity before fetching; never replay rate-limit events.
  void replaceAccountSession(AgentAccountSession session) {
    if (!_available || source != QuotaAnswerSource.codexAccount) return;
    invalidate(forget: true);
    _closeSession();
    _listen(session);
  }

  /// Offline/background: retain the last observation and mark it stale.
  /// Profile deletion/account changes: pass forget:true to erase it immediately.
  void invalidate({bool forget = false}) {
    if (_disposed) return;
    ++_revision;
    _closeCollector();
    _expiry?.cancel();
    _expiry = null;
    _loading = false;
    _stale = true;
    _attention = false;
    _status = QuotaAnswerStatus.unavailable;
    if (forget || !isCurrent()) {
      _snapshot = null;
      _accountIdentity = null;
      _collectorIdentity = null;
      _alerted.clear();
    }
    _notify();
  }

  Future<void> refresh() async {
    if (!_available) {
      invalidate(forget: true);
      return;
    }
    final revision = ++_revision;
    _closeCollector();
    _loading = true;
    _attention = false;
    _notify();
    try {
      if (!_current(revision)) return;
      if (source == QuotaAnswerSource.codexAccount) {
        await _readAccount(revision);
      } else {
        await _readCollector(revision);
      }
    } catch (error) {
      if (!_current(revision)) return;
      _stale = true;
      // No raw exception survives: transports can include credentials in it.
      _status = switch (error) {
        ProviderQuotaFailure(kind: QuotaFailureKind.unsupported) =>
          QuotaAnswerStatus.needsCollector,
        ProviderQuotaFailure(kind: QuotaFailureKind.collectorAuth) =>
          QuotaAnswerStatus.collectorAuth,
        ProviderQuotaFailure(kind: QuotaFailureKind.invalidResponse) ||
        AgentAccountException(kind: AgentAccountFailure.invalidResponse) ||
        FormatException() => QuotaAnswerStatus.invalidResponse,
        _ => QuotaAnswerStatus.unavailable,
      };
      // Auth failures cannot attest that the old account is still selected.
      if (_status == QuotaAnswerStatus.collectorAuth) _snapshot = null;
    } finally {
      if (_current(revision)) {
        _closeCollector();
        _loading = false;
        _notify();
      }
    }
  }

  Future<void> _readAccount(int revision) async {
    final session = _session!;
    if (!session.active) {
      _stale = true;
      _status = QuotaAnswerStatus.unavailable;
      return;
    }
    if (!session.supported) {
      _replaceStatus(QuotaAnswerStatus.unsupported);
      return;
    }
    final account = await session.read();
    if (!_current(revision)) return;
    if (!session.active) {
      invalidate();
      return;
    }
    if (!account.signedIn) {
      _replaceStatus(QuotaAnswerStatus.needsSignIn);
      return;
    }
    if (account.type != 'chatgpt') {
      _replaceStatus(QuotaAnswerStatus.unsupported);
      return;
    }
    final previous = _accountIdentity;
    if (previous != null &&
        (previous.type != account.type || previous.email != account.email)) {
      _snapshot = null;
      _alerted.clear();
      _stale = true;
      _status = QuotaAnswerStatus.unavailable;
      _notify();
    }
    if (!_current(revision)) return;
    _accountIdentity = account;
    final buckets = await session.rateLimits();
    if (!_current(revision)) return;
    if (!session.active) {
      invalidate();
      return;
    }
    if (buckets.length > 32) throw const FormatException();
    final windows = <QuotaAnswerWindow>[];
    for (var index = 0; index < buckets.length; index++) {
      final bucket = buckets[index];
      for (final entry in {
        'primary': bucket.primary,
        'secondary': bucket.secondary,
      }.entries) {
        final window = entry.value;
        if (window == null) continue;
        if (window.usedPercent < 0 ||
            window.usedPercent > 100 ||
            (window.durationMinutes != null && window.durationMinutes! <= 0)) {
          throw const FormatException();
        }
        windows.add(
          QuotaAnswerWindow(
            id: '$index.${entry.key}',
            usedPercent: window.usedPercent.toDouble(),
            durationMinutes: window.durationMinutes,
            resetsAt: window.resetsAt,
          ),
        );
      }
    }
    _accept(
      QuotaAnswerSnapshot(
        source: source,
        observedAt: clock(),
        windows: windows,
      ),
      stale: false,
    );
  }

  Future<void> _readCollector(int revision) async {
    final gateway = _collectorFactory!();
    if (!_current(revision)) {
      _safeClose(gateway);
      return;
    }
    _collector = gateway;
    final result = await gateway.readSnapshot();
    if (!_current(revision)) return;
    if (!quotaCollectionAvailable(result.provider)) {
      _replaceStatus(QuotaAnswerStatus.unsupported);
      return;
    }
    if (!result.canShowWindows) {
      final sameAccount =
          _collectorIdentity == (result.provider, result.account.ref);
      if (sameAccount &&
          (result.status == ProviderQuotaStatus.unavailable ||
              result.status == ProviderQuotaStatus.rateLimited)) {
        _stale = true;
        _status = QuotaAnswerStatus.unavailable;
        return;
      }
      _replaceStatus(switch (result.status) {
        ProviderQuotaStatus.unconfigured => QuotaAnswerStatus.needsCollector,
        ProviderQuotaStatus.authRequired => QuotaAnswerStatus.needsSignIn,
        ProviderQuotaStatus.unsupported => QuotaAnswerStatus.unsupported,
        ProviderQuotaStatus.invalidResponse ||
        ProviderQuotaStatus.ok => QuotaAnswerStatus.invalidResponse,
        _ => QuotaAnswerStatus.unavailable,
      });
      return;
    }
    final identity = (result.provider, result.account.ref);
    if (_collectorIdentity != identity) _alerted.clear();
    _collectorIdentity = identity;
    _accept(
      QuotaAnswerSnapshot(
        source: source,
        observedAt: result.fetchedAt,
        windows: [
          for (final window in result.windows)
            if (window.status == QuotaWindowStatus.reported)
              QuotaAnswerWindow(
                id: window.id,
                usedPercent: window.usedPercent!,
                durationMinutes: window.durationSeconds == null
                    ? null
                    : (window.durationSeconds! % 60 == 0
                          ? window.durationSeconds! ~/ 60
                          : null),
                resetsAt: window.resetsAt,
              ),
        ],
      ),
      stale:
          result.freshness != QuotaFreshness.fresh ||
          result.isStale(clock()) ||
          clock().isBefore(result.fetchedAt),
      expiresAt: result.expiresAt,
    );
  }

  void _replaceStatus(QuotaAnswerStatus status) {
    _expiry?.cancel();
    _expiry = null;
    _snapshot = null;
    _status = status;
    _stale = true;
    _attention = false;
    _alerted.clear();
    _accountIdentity = null;
    _collectorIdentity = null;
  }

  void _accept(
    QuotaAnswerSnapshot value, {
    required bool stale,
    DateTime? expiresAt,
  }) {
    _snapshot = value;
    _expiresAt = expiresAt;
    _status = value.windows.isEmpty
        ? QuotaAnswerStatus.unavailable
        : QuotaAnswerStatus.ready;
    _stale = stale || value.isExpired(clock());
    if (!_stale && alert80Enabled) {
      for (final window in value.windows) {
        if (window.usedPercent < 80) continue;
        final marker =
            '${window.id}:${window.resetsAt?.millisecondsSinceEpoch}';
        if (_alerted.add(marker)) _attention = true;
      }
    }
    _expiry?.cancel();
    var expiry = expiresAt;
    for (final window in value.windows) {
      final reset = window.resetsAt;
      if (reset != null && (expiry == null || reset.isBefore(expiry))) {
        expiry = reset;
      }
    }
    if (!_stale && expiry != null && expiry.isAfter(clock())) {
      _expiry = Timer(expiry.difference(clock()), () {
        _stale = true;
        _attention = false;
        _notify();
      });
    }
  }

  bool _current(int revision) => _available && revision == _revision;
  void _notify() {
    if (!_disposed) notifyListeners();
  }

  static void _safeClose(ProviderQuotaGateway gateway) {
    try {
      gateway.close();
    } catch (_) {}
  }

  void _closeCollector() {
    final gateway = _collector;
    _collector = null;
    if (gateway != null) _safeClose(gateway);
  }

  void _closeSession() {
    unawaited(_events?.cancel());
    _events = null;
    final session = _session;
    _session = null;
    if (session != null) {
      unawaited(Future<void>.sync(session.close).catchError((Object _) {}));
    }
  }

  @override
  void dispose() {
    if (_disposed) return;
    _disposed = true;
    ++_revision;
    _snapshot = null;
    _accountIdentity = null;
    _collectorIdentity = null;
    _alerted.clear();
    _expiry?.cancel();
    _closeCollector();
    _closeSession();
    super.dispose();
  }
}
